// lib/duaDatabase3.ts
// More authentic duas — Batch 3 (73-150)

import { type Dua } from './duaDatabase';

export const DUAS_BATCH3: Dua[] = [
  // PRAYER & WORSHIP (73-90)
  { id: 73, arabic: 'سُبْحَانَ رَبِّيَ الْعَظِيمِ', transliteration: 'Subhana Rabbiyal-Adheem', translation: 'Glory be to my Lord, the Most Great.', reference: 'Muslim, Abu Dawud', category: 'prayer', occasion: 'In ruku — say 3 times', tags: ['prayer', 'ruku', 'salah'] },
  { id: 74, arabic: 'سُبْحَانَ رَبِّيَ الْأَعْلَى', transliteration: 'Subhana Rabbiyal-Ala', translation: 'Glory be to my Lord, the Most High.', reference: 'Muslim, Abu Dawud', category: 'prayer', occasion: 'In sujood — say 3 times', tags: ['prayer', 'sujood', 'salah'] },
  { id: 75, arabic: 'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ رَبَّنَا وَلَكَ الْحَمْدُ', transliteration: 'Sami Allahu liman hamidah, Rabbana wa lakal hamd', translation: 'Allah hears the one who praises Him. Our Lord, to You belongs all praise.', reference: 'Sahih Bukhari, Muslim', category: 'prayer', occasion: 'Rising from ruku', tags: ['prayer', 'ruku'] },
  { id: 76, arabic: 'رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي', transliteration: 'Rabbighfir li, Rabbighfir li', translation: 'My Lord, forgive me. My Lord, forgive me.', reference: 'Abu Dawud (Sahih)', category: 'prayer', occasion: 'Between the two sajdahs', tags: ['prayer', 'sajdah'] },
  { id: 77, arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ', transliteration: 'Allahumma ainni ala dhikrika wa shukrika wa husni ibadatik', translation: 'O Allah, help me to remember You, thank You, and worship You in the best way.', reference: 'Abu Dawud, Nasai (Sahih)', category: 'prayer', occasion: 'After every prayer', virtue: 'The Prophet advised Muadh to never leave this dua', tags: ['prayer', 'after prayer'] },
  { id: 78, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ', transliteration: 'Allahumma inni asalukal-jannata wa aoodhu bika minan-nar', translation: 'O Allah, I ask You for Paradise and seek refuge in You from the Fire.', reference: 'Abu Dawud (Sahih)', category: 'prayer', occasion: 'After every prayer', virtue: 'Paradise asks Allah to admit him, Fire asks Allah to protect him', tags: ['prayer', 'paradise', 'fire'] },
  { id: 79, arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ', transliteration: 'Allahumma antas-Salamu wa minkas-salam tabarakta ya dhal-jalali wal-ikram', translation: 'O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of Majesty and Honour.', reference: 'Muslim 1/414', category: 'prayer', occasion: 'Immediately after salam in prayer', tags: ['prayer', 'after prayer', 'salam'] },
  { id: 80, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى', transliteration: 'Allahumma inni asalukal-huda wat-tuqa wal-afafa wal-ghina', translation: 'O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.', reference: 'Muslim 4/2087', category: 'prayer', occasion: 'General comprehensive dua', tags: ['prayer', 'guidance', 'comprehensive'] },
  { id: 81, arabic: 'اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي', transliteration: 'Allahumma-hdini wa saddidni', translation: 'O Allah, guide me and keep me on the right path.', reference: 'Muslim 4/2090', category: 'prayer', occasion: 'Daily dua for guidance', tags: ['prayer', 'guidance'] },
  { id: 82, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ وَمِنْ عَذَابِ النَّارِ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ وَمِنْ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ', transliteration: 'Allahumma inni aoodhu bika min adhabil-qabri wa min adhabi-nar wa min fitnatil-mahya wal-mamati wa min fitnatil-masihid-dajjal', translation: 'O Allah, I seek refuge in You from the punishment of the grave, the punishment of the Fire, the trials of life and death, and the trial of the False Messiah.', reference: 'Sahih Bukhari, Muslim', category: 'prayer', occasion: 'In the last tashahhud before salam', tags: ['prayer', 'tashahhud', 'protection'] },
  // RIZQ & PROVISION (83-95)
  { id: 83, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا', transliteration: 'Allahumma inni asaluka ilman naafian wa rizqan tayyiban wa amalan mutaqabbala', translation: 'O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.', reference: 'Ibn Majah (Sahih)', category: 'rizq', occasion: 'After Fajr prayer', tags: ['rizq', 'knowledge', 'morning'] },
  { id: 84, arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ', transliteration: 'Allahummak-fini bihalalika an haramika wa aghnini bifadlika amman siwak', translation: 'O Allah, suffice me with what You have allowed instead of what You have forbidden, and make me independent of all others besides You.', reference: 'Tirmidhi 5/560', category: 'rizq', occasion: 'When in debt or financial difficulty', virtue: 'Even if debt is like a mountain, Allah will pay it off', tags: ['rizq', 'debt', 'halal'] },
  { id: 85, arabic: 'رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ', transliteration: 'Rabbi inni lima anzalta ilayya min khayrin faqeer', translation: 'My Lord, indeed I am, for whatever good You would send down to me, in need.', reference: 'Quran 28:24', category: 'rizq', occasion: 'When in need — dua of Musa (AS)', virtue: 'Allah immediately provided for Musa after this dua', tags: ['rizq', 'need', 'quran', 'musa'] },
  { id: 86, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْفَقْرِ وَالْقِلَّةِ وَالذِّلَّةِ', transliteration: 'Allahumma inni aoodhu bika minal-faqri wal-qillati wadh-dhillah', translation: 'O Allah, I seek refuge in You from poverty, scarcity, and humiliation.', reference: 'Abu Dawud, Nasai (Sahih)', category: 'rizq', occasion: 'Protection from poverty', tags: ['rizq', 'poverty', 'protection'] },
  { id: 87, arabic: 'اللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي', transliteration: 'Allahumma aslih li deeni alladhi huwa ismatu amri wa aslih li dunyaya allati fiha maashi', translation: 'O Allah, rectify for me my religion which is the safeguard of my affairs, and rectify for me my worldly affairs wherein is my livelihood.', reference: 'Muslim 4/2087', category: 'rizq', occasion: 'Comprehensive dua for dunya and akhirah', tags: ['rizq', 'comprehensive', 'dunya'] },
  // KNOWLEDGE (88-95)
  { id: 88, arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي', transliteration: 'Rabbish-rahli sadri wa yassir li amri', translation: 'My Lord, expand for me my chest and ease my task for me.', reference: 'Quran 20:25-26', category: 'knowledge', occasion: 'Before exam, presentation, or speech', tags: ['knowledge', 'exam', 'quran', 'musa'] },
  { id: 89, arabic: 'رَبِّ زِدْنِي عِلْمًا', transliteration: 'Rabbi zidni ilma', translation: 'My Lord, increase me in knowledge.', reference: 'Quran 20:114', category: 'knowledge', occasion: 'When studying or seeking knowledge', tags: ['knowledge', 'study', 'quran'] },
  { id: 90, arabic: 'اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا', transliteration: 'Allahumma-nfani bima allamtani wa allimni ma yanfauni wa zidni ilma', translation: 'O Allah, benefit me with what You have taught me, teach me what will benefit me, and increase me in knowledge.', reference: 'Tirmidhi, Ibn Majah', category: 'knowledge', occasion: 'After studying', tags: ['knowledge', 'study'] },
  { id: 91, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ وَمِنْ قَلْبٍ لَا يَخْشَعُ', transliteration: 'Allahumma inni aoodhu bika min ilmin la yanfa wa min qalbin la yakhsha', translation: 'O Allah, I seek refuge in You from knowledge that does not benefit and a heart that does not fear.', reference: 'Muslim 4/2088', category: 'knowledge', occasion: 'Daily — protection from useless knowledge', tags: ['knowledge', 'protection', 'heart'] },
  // LIFE EVENTS (92-105)
  { id: 92, arabic: 'بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ', transliteration: 'Barakallahu laka wa baraka alayka wa jamaa baynakuma fi khayr', translation: 'May Allah bless you, shower blessings upon you, and join you together in goodness.', reference: 'Abu Dawud, Tirmidhi (Sahih)', category: 'life', occasion: 'Congratulating a newly married couple', tags: ['life', 'marriage', 'wedding'] },
  { id: 93, arabic: 'رَبِّ هَبْ لِي مِنْ لَدُنْكَ ذُرِّيَّةً طَيِّبَةً إِنَّكَ سَمِيعُ الدُّعَاءِ', transliteration: 'Rabbi hab li min ladunka dhurriyyatan tayyibah innaka sameeud-duaa', translation: 'My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.', reference: 'Quran 3:38', category: 'life', occasion: 'Dua for children — dua of Zakariyya (AS)', tags: ['life', 'children', 'quran'] },
  { id: 94, arabic: 'رَبِّ لَا تَذَرْنِي فَرْدًا وَأَنْتَ خَيْرُ الْوَارِثِينَ', transliteration: 'Rabbi la tadharnee fardan wa anta khayrul-waritheen', translation: 'My Lord, do not leave me alone, and You are the best of inheritors.', reference: 'Quran 21:89', category: 'life', occasion: 'When wanting children or feeling lonely', tags: ['life', 'children', 'loneliness', 'quran'] },
  { id: 95, arabic: 'اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ', transliteration: 'Allahummagh-fir lahu warhamhu wa aafihi wafu anhu', translation: 'O Allah, forgive him, have mercy on him, give him peace, and pardon him.', reference: 'Muslim 2/663', category: 'life', occasion: 'Funeral prayer — dua for the deceased', tags: ['life', 'death', 'funeral'] },
  { id: 96, arabic: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا', transliteration: 'Rabbir-hamhuma kama rabbayani sagheera', translation: 'My Lord, have mercy upon them (my parents) as they brought me up when I was small.', reference: 'Quran 17:24', category: 'home', occasion: 'Dua for parents — recite daily', tags: ['home', 'parents', 'quran'] },
  // EVENTS (97-105)
  { id: 97, arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ', transliteration: 'Dhahaba adh-dhama-u wabtallatil-urooqu wa thabatal-ajru in shaa Allah', translation: 'The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.', reference: 'Abu Dawud 2/306', category: 'events', occasion: 'When breaking fast (Iftar)', tags: ['events', 'ramadan', 'iftar'] },
  { id: 98, arabic: 'لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ', transliteration: 'Labbayk Allahumma labbayk labbayka la shareeka laka labbayk', translation: 'Here I am O Allah, here I am. Here I am, You have no partner, here I am.', reference: 'Sahih Bukhari, Muslim', category: 'events', occasion: 'Talbiyah — during Hajj and Umrah', tags: ['events', 'hajj', 'umrah'] },
  { id: 99, arabic: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ', transliteration: 'Rabbana taqabbal minna innaka antas-Sameeul-Aleem', translation: 'Our Lord, accept from us. Indeed, You are the All-Hearing, the All-Knowing.', reference: 'Quran 2:127', category: 'events', occasion: 'After any good deed — dua of Ibrahim (AS)', tags: ['events', 'acceptance', 'quran'] },
  { id: 100, arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ', transliteration: 'Allahumma salli ala Muhammadin wa ala aali Muhammad kama sallayta ala Ibrahim', translation: 'O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon Ibrahim.', reference: 'Sahih Bukhari, Muslim', category: 'events', occasion: 'Durood Ibrahim — in prayer and on Fridays', virtue: 'Whoever sends one salawat, Allah sends 10 blessings upon him', tags: ['events', 'friday', 'salawat'] },
  // QURAN DUAS (101-115)
  { id: 101, arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ', transliteration: 'Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina adhaban-nar', translation: 'Our Lord, give us in this world good and in the Hereafter good, and protect us from the Fire.', reference: 'Quran 2:201', category: 'prayer', occasion: 'Most comprehensive dua — use anytime', virtue: 'The most frequent dua of the Prophet (peace be upon him)', tags: ['quran', 'comprehensive', 'popular'] },
  { id: 102, arabic: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً', transliteration: 'Rabbana la tuzigh quloobana bada idh hadaytana wa hab lana min ladunka rahmah', translation: 'Our Lord, let not our hearts deviate after You have guided us and grant us mercy from Yourself.', reference: 'Quran 3:8', category: 'prayer', occasion: 'Dua for steadfastness on guidance', tags: ['quran', 'guidance', 'heart'] },
  { id: 103, arabic: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ', transliteration: 'Rabbana afrigh alayna sabran wa thabbit aqdamana wansurna alal-qawmil-kafireen', translation: 'Our Lord, pour upon us patience, make our feet firm, and give us victory.', reference: 'Quran 2:250', category: 'anxiety', occasion: 'When facing a difficult challenge', tags: ['quran', 'patience', 'victory'] },
  { id: 104, arabic: 'رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا', transliteration: 'Rabbana wa la tuhammilna ma la taqata lana bihi wafu anna waghfir lana warhamna', translation: 'Our Lord, do not burden us beyond our capacity. Pardon us, forgive us, and have mercy on us.', reference: 'Quran 2:286', category: 'forgiveness', occasion: 'When feeling burdened', tags: ['quran', 'mercy', 'burden'] },
  { id: 105, arabic: 'رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَى وَالِدَيَّ', transliteration: 'Rabbi awzini an ashkura nimataka allati anamta alayya wa ala walidayya', translation: 'My Lord, enable me to be grateful for Your favour upon me and upon my parents.', reference: 'Quran 27:19', category: 'home', occasion: 'Dua for gratitude', tags: ['quran', 'gratitude', 'parents'] },
  { id: 106, arabic: 'رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ', transliteration: 'Rabbana innana amanna faghfir lana dhunubana wa qina adhaban-nar', translation: 'Our Lord, indeed we have believed, so forgive us our sins and protect us from the Fire.', reference: 'Quran 3:16', category: 'forgiveness', occasion: 'Seeking forgiveness after affirming faith', tags: ['quran', 'forgiveness', 'fire'] },
  { id: 107, arabic: 'رَبَّنَا مَا خَلَقْتَ هَذَا بَاطِلًا سُبْحَانَكَ فَقِنَا عَذَابَ النَّارِ', transliteration: 'Rabbana ma khalaqta hadha batilan subhanaka faqina adhaban-nar', translation: 'Our Lord, You did not create this in vain. Glory be to You. Protect us from the Fire.', reference: 'Quran 3:191', category: 'prayer', occasion: 'When reflecting on creation', tags: ['quran', 'reflection', 'fire'] },
  { id: 108, arabic: 'رَبَّنَا إِنَّكَ مَنْ تُدْخِلِ النَّارَ فَقَدْ أَخْزَيْتَهُ وَمَا لِلظَّالِمِينَ مِنْ أَنْصَارٍ', transliteration: 'Rabbana innaka man tudkhilin-nara faqad akhzaytahu wa ma lidh-dhalimeena min ansar', translation: 'Our Lord, indeed whoever You admit to the Fire — You have disgraced him, and for the wrongdoers there are no helpers.', reference: 'Quran 3:192', category: 'prayer', occasion: 'Seeking protection from the Fire', tags: ['quran', 'fire', 'protection'] },
  { id: 109, arabic: 'رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا وَتَوَفَّنَا مَعَ الْأَبْرَارِ', transliteration: 'Rabbana faghfir lana dhunubana wa kaffir anna sayyiatina wa tawaffana maal-abrar', translation: 'Our Lord, forgive us our sins, remove from us our misdeeds, and cause us to die with the righteous.', reference: 'Quran 3:193', category: 'forgiveness', occasion: 'Seeking a good death', tags: ['quran', 'forgiveness', 'death', 'righteous'] },
  { id: 110, arabic: 'رَبَّنَا وَآتِنَا مَا وَعَدْتَنَا عَلَى رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ', transliteration: 'Rabbana wa atina ma waadtana ala rusulika wa la tukhzina yawmal-qiyamah', translation: 'Our Lord, grant us what You promised us through Your messengers and do not disgrace us on the Day of Resurrection.', reference: 'Quran 3:194', category: 'prayer', occasion: 'Seeking fulfillment of promises', tags: ['quran', 'judgement', 'promise'] },
  { id: 111, arabic: 'رَبَّنَا اصْرِفْ عَنَّا عَذَابَ جَهَنَّمَ إِنَّ عَذَابَهَا كَانَ غَرَامًا', transliteration: 'Rabbanas-rif anna adhaba jahannama inna adhabaha kana gharama', translation: 'Our Lord, avert from us the punishment of Hell. Indeed, its punishment is ever adhering.', reference: 'Quran 25:65', category: 'protection', occasion: 'Seeking protection from Hell', tags: ['quran', 'fire', 'hell', 'protection'] },
  { id: 112, arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا', transliteration: 'Rabbana hab lana min azwajina wa dhurriyyatina qurrata ayunin wajalna lil-muttaqeena imama', translation: 'Our Lord, grant us from our spouses and offspring comfort to our eyes and make us leaders for the righteous.', reference: 'Quran 25:74', category: 'home', occasion: 'Dua for family happiness', tags: ['quran', 'family', 'spouse', 'children'] },
  { id: 113, arabic: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِنْ ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ', transliteration: 'Rabbij-alni muqeemas-salati wa min dhurriyyati Rabbana wa taqabbal duaa', translation: 'My Lord, make me an establisher of prayer, and from my descendants. Our Lord, accept my supplication.', reference: 'Quran 14:40', category: 'prayer', occasion: 'Dua for prayer consistency', tags: ['quran', 'prayer', 'children'] },
  { id: 114, arabic: 'رَبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ وَاجْعَلْ لِي مِنْ لَدُنْكَ سُلْطَانًا نَصِيرًا', transliteration: 'Rabbi adkhilni mudkhala sidqin wa akhrijni mukhraja sidqin wajal li min ladunka sultanan naseera', translation: 'My Lord, cause me to enter a sound entrance and exit a sound exit, and grant me a supporting authority.', reference: 'Quran 17:80', category: 'home', occasion: 'When entering or leaving any place', tags: ['quran', 'entering', 'leaving'] },
  { id: 115, arabic: 'رَبَّنَا آمَنَّا فَاغْفِرْ لَنَا وَارْحَمْنَا وَأَنْتَ خَيْرُ الرَّاحِمِينَ', transliteration: 'Rabbana amanna faghfir lana warhamna wa anta khayrur-rahimeen', translation: 'Our Lord, we have believed, so forgive us and have mercy upon us, and You are the best of the merciful.', reference: 'Quran 23:109', category: 'forgiveness', occasion: 'Seeking mercy and forgiveness', tags: ['quran', 'forgiveness', 'mercy'] },
];
