// lib/duaDatabase4.ts
// Batch 4 — 50 more authentic duas (116-165)

import { type Dua } from './duaDatabase';

export const DUAS_BATCH4: Dua[] = [
  // MORNING/EVENING ADHKAR (116-125)
  { id: 116, arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ', transliteration: 'Subhanallahi wa bihamdihi adada khalqihi wa rida nafsihi wa zinata arshihi wa midada kalimatih', translation: 'Glory and praise be to Allah, as many as His creation, as much as pleases Him, as much as the weight of His Throne, and as much as the ink of His words.', reference: 'Muslim 4/2090', category: 'morning', occasion: 'Say 3 times in the morning', virtue: 'Equal to hours of dhikr', tags: ['morning', 'dhikr', 'reward'] },
  { id: 117, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ', transliteration: 'Allahumma inni asalukal-afwa wal-afiyata fid-dunya wal-akhirah', translation: 'O Allah, I ask You for pardon and well-being in this life and the next.', reference: 'Abu Dawud, Ibn Majah (Sahih)', category: 'morning', occasion: 'Morning and evening — never leave this dua', virtue: 'The Prophet never left this dua morning and evening', tags: ['morning', 'evening', 'essential'] },
  { id: 118, arabic: 'أَصْبَحْنَا عَلَى فِطْرَةِ الْإِسْلَامِ وَعَلَى كَلِمَةِ الْإِخْلَاصِ وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ', transliteration: 'Asbahna ala fitratil-Islam wa ala kalimatil-ikhlas wa ala deeni nabiyyina Muhammad wa ala millati abeena Ibrahim', translation: 'We rise upon the fitrah of Islam, the word of sincerity, the religion of our Prophet Muhammad, and the way of our father Ibrahim.', reference: 'Ahmad 3/406 (Sahih)', category: 'morning', occasion: 'Every morning', tags: ['morning', 'islam', 'fitrah'] },
  { id: 119, arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ', transliteration: 'Subhanallahi wa bihamdih', translation: 'Glory and praise be to Allah.', reference: 'Sahih Bukhari, Muslim', category: 'morning', occasion: 'Say 100 times morning and evening', virtue: 'Sins forgiven even if like the foam of the sea', tags: ['morning', 'evening', '100 times'] },
  { id: 120, arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', transliteration: 'La ilaha illallahu wahdahu la shareeka lahu lahul-mulku wa lahul-hamdu wa huwa ala kulli shayin qadeer', translation: 'None has the right to be worshipped except Allah alone, without partner. To Him belongs sovereignty and praise, and He is over all things capable.', reference: 'Sahih Bukhari, Muslim', category: 'morning', occasion: 'Say 100 times — morning and evening', virtue: '100 good deeds, 100 sins erased, protection from Shaytan all day', tags: ['morning', 'evening', '100 times', 'tawheed'] },
  { id: 121, arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ', transliteration: 'Ya Hayyu ya Qayyoomu bi-rahmatika astagheethu aslih li shani kullahu wa la takilni ila nafsi tarfata ayn', translation: 'O Living, O Self-Sustaining, in Your mercy I seek relief. Rectify all my affairs and do not leave me to myself even for the blink of an eye.', reference: 'Hakim (Sahih)', category: 'morning', occasion: 'Morning and evening', tags: ['morning', 'evening', 'comprehensive'] },
  { id: 122, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ فَتْحَهُ وَنَصْرَهُ وَنُورَهُ وَبَرَكَتَهُ وَهُدَاهُ', transliteration: 'Allahumma inni asaluka khayra hadhal-yawmi fathahu wa nasrahu wa noorahu wa barakatahu wa hudah', translation: 'O Allah, I ask You for the good of this day — its opening, its victory, its light, its blessing, and its guidance.', reference: 'Abu Dawud (Hasan)', category: 'morning', occasion: 'Every morning', tags: ['morning', 'daily', 'barakah'] },
  { id: 123, arabic: 'اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ', transliteration: 'Allahumma ma amsa bi min nimatin aw bi-ahadin min khalqika faminka wahdaka la shareeka lak', translation: 'O Allah, whatever blessing I or any of Your creation have received this evening, is from You alone, without partner.', reference: 'Abu Dawud 4/318', category: 'evening', occasion: 'Every evening', virtue: 'Fulfills gratitude for that evening', tags: ['evening', 'gratitude'] },
  { id: 124, arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ رَبِّ الْعَالَمِينَ', transliteration: 'Amsayna wa amsal-mulku lillahi Rabbil-aalameen', translation: 'We have reached the evening and the dominion belongs to Allah, Lord of all worlds.', reference: 'Muslim', category: 'evening', occasion: 'Every evening', tags: ['evening', 'daily'] },
  { id: 125, arabic: 'اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلَّا أَنْتَ', transliteration: 'Allahumma inni amsaytu ushhiduka wa ushhidu hamalata arshika wa malaikataka annaka antallahu la ilaha illa ant', translation: 'O Allah, I have reached the evening and call You, the bearers of Your throne, Your angels to witness that You are Allah, none worthy of worship except You.', reference: 'Abu Dawud 4/317', category: 'evening', occasion: 'Say 4 times every evening', virtue: 'Allah frees a quarter of him from the Fire each time', tags: ['evening', 'protection', 'fire'] },
  // SLEEP (126-132)
  { id: 126, arabic: 'اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَأَحْيَا', transliteration: 'Allahumma bismika amootu wa ahya', translation: 'O Allah, in Your name I die and I live.', reference: 'Sahih Bukhari 11/113', category: 'sleep', occasion: 'When going to sleep', tags: ['sleep', 'night'] },
  { id: 127, arabic: 'بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي وَبِكَ أَرْفَعُهُ إِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ', transliteration: 'Bismika Rabbi wadatu janbi wa bika arfauhu in amsakta nafsi farhamha wa in arsaltaha fahfadhha bima tahfadhu bihi ibadakas-saliheen', translation: 'In Your name my Lord, I lie down and in Your name I rise. If You take my soul, have mercy on it, and if You return it, protect it as You protect Your righteous servants.', reference: 'Sahih Bukhari, Muslim', category: 'sleep', occasion: 'When lying down to sleep', tags: ['sleep', 'night', 'protection'] },
  { id: 128, arabic: 'اللَّهُمَّ إِنَّكَ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا لَكَ مَمَاتُهَا وَمَحْيَاهَا إِنْ أَحْيَيْتَهَا فَاحْفَظْهَا وَإِنْ أَمَتَّهَا فَاغْفِرْ لَهَا', transliteration: 'Allahumma innaka khalaqta nafsi wa anta tawaffaha laka mamatuha wa mahyaha in ahyaytaha fahfadhha wa in amattaha faghfir laha', translation: 'O Allah, You created my soul and You take it back. To You belongs its death and life. If You give it life, protect it, and if You cause it to die, forgive it.', reference: 'Muslim 4/2083', category: 'sleep', occasion: 'Before sleeping', tags: ['sleep', 'night'] },
  { id: 129, arabic: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ', transliteration: 'Allahumma qini adhabaka yawma tabathu ibadak', translation: 'O Allah, protect me from Your punishment on the day You resurrect Your servants.', reference: 'Abu Dawud 4/311', category: 'sleep', occasion: 'Before sleeping — say 3 times', tags: ['sleep', 'protection', 'judgement'] },
  { id: 130, arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ', transliteration: 'Alhamdu lillahil-ladhi ahyana bada ma amatana wa ilayhin-nushoor', translation: 'All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.', reference: 'Sahih Bukhari 11/113', category: 'sleep', occasion: 'Upon waking up', tags: ['sleep', 'waking', 'morning'] },
  { id: 131, arabic: 'الْحَمْدُ لِلَّهِ الَّذِي عَافَانِي فِي جَسَدِي وَرَدَّ عَلَيَّ رُوحِي وَأَذِنَ لِي بِذِكْرِهِ', transliteration: 'Alhamdu lillahil-ladhi aafani fi jasadi wa radda alayya roohi wa adhina li bidhikrih', translation: 'All praise is for Allah who restored my body, returned my soul, and permitted me to remember Him.', reference: 'Tirmidhi 5/473', category: 'sleep', occasion: 'Upon waking up', tags: ['sleep', 'waking', 'gratitude'] },
  { id: 132, arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ', transliteration: 'La ilaha illallahu wahdahu la shareeka lahu lahul-mulku wa lahul-hamdu wa huwa ala kulli shayin qadeer. Subhanallahi walhamdulillahi wa la ilaha illallahu wallahu akbar wa la hawla wa la quwwata illa billahil-aliyyil-adheem', translation: 'None has the right to be worshipped except Allah alone, without partner... Glory be to Allah, praise be to Allah, none has the right to be worshipped except Allah, Allah is the Greatest, and there is no might nor power except with Allah, the Most High, the Most Great.', reference: 'Sahih Bukhari', category: 'sleep', occasion: 'When waking at night — then make dua', virtue: 'Whoever says this then makes dua, it will be answered. If he prays, his prayer will be accepted.', tags: ['sleep', 'night', 'tahajjud', 'accepted'] },
  // TRAVEL (133-140)
  { id: 133, arabic: 'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى', transliteration: 'Allahumma inna nasaluka fi safarina hadhal-birra wat-taqwa wa minal-amali ma tarda', translation: 'O Allah, we ask You on this journey for righteousness, piety, and deeds that please You.', reference: 'Muslim 2/978', category: 'travel', occasion: 'Starting any journey', tags: ['travel', 'journey'] },
  { id: 134, arabic: 'اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ', transliteration: 'Allahumma hawwin alayna safarana hadha watwi anna budah', translation: 'O Allah, make this journey easy for us and shorten its distance.', reference: 'Muslim 2/978', category: 'travel', occasion: 'During travel', tags: ['travel', 'ease'] },
  { id: 135, arabic: 'اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الْأَهْلِ', transliteration: 'Allahumma antas-sahibu fis-safari wal-khaleefatu fil-ahl', translation: 'O Allah, You are the Companion on the journey and the Guardian of the family.', reference: 'Muslim 2/978', category: 'travel', occasion: 'When leaving family for travel', tags: ['travel', 'family'] },
  { id: 136, arabic: 'أَسْتَوْدِعُكُمُ اللَّهَ الَّذِي لَا تَضِيعُ وَدَائِعُهُ', transliteration: 'Astawdiukumullaha alladhi la tadee-u wadaiuh', translation: 'I entrust you to Allah, whose trusts are never lost.', reference: 'Ahmad, Ibn Majah (Sahih)', category: 'travel', occasion: 'Saying goodbye to someone', tags: ['travel', 'farewell'] },
  { id: 137, arabic: 'أَسْتَوْدِعُ اللَّهَ دِينَكَ وَأَمَانَتَكَ وَخَوَاتِيمَ عَمَلِكَ', transliteration: 'Astawdi-ullaha deenaka wa amanataka wa khawateema amalik', translation: 'I entrust to Allah your religion, your trust, and the last of your deeds.', reference: 'Abu Dawud, Tirmidhi', category: 'travel', occasion: 'Saying farewell to a traveller', tags: ['travel', 'farewell'] },
  { id: 138, arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ', transliteration: 'Aayiboona taaiboona aabidoona li-Rabbina hamidoon', translation: 'We return repenting, worshipping, and praising our Lord.', reference: 'Muslim 2/980', category: 'travel', occasion: 'When returning from travel', tags: ['travel', 'return'] },
  { id: 139, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ وَكَآبَةِ الْمَنْظَرِ وَسُوءِ الْمُنْقَلَبِ', transliteration: 'Allahumma inni aoodhu bika min wathaa-is-safari wa kaabatil-mandhari wa soo-il-munqalab', translation: 'O Allah, I seek refuge in You from the hardship of travel, a depressing sight, and a bad return.', reference: 'Muslim 2/978', category: 'travel', occasion: 'During travel', tags: ['travel', 'protection'] },
  { id: 140, arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ', transliteration: 'Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrineen wa inna ila Rabbina lamunqaliboon', translation: 'Glory to Him who has subjected this to us, and we could never have it by our efforts, and to our Lord we shall return.', reference: 'Quran 43:13-14', category: 'travel', occasion: 'When riding any vehicle', tags: ['travel', 'vehicle', 'quran'] },
  // HOME & FAMILY (141-150)
  { id: 141, arabic: 'بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى رَبِّنَا تَوَكَّلْنَا', transliteration: 'Bismillahi walajna wa bismillahi kharajna wa ala Rabbina tawakkalna', translation: 'In the name of Allah we enter and in the name of Allah we leave, and upon our Lord we rely.', reference: 'Abu Dawud 4/325', category: 'home', occasion: 'When entering the home', tags: ['home', 'entering'] },
  { id: 142, arabic: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ', transliteration: 'Bismillahi tawakkaltu alallahi la hawla wa la quwwata illa billah', translation: 'In the name of Allah, I place my trust in Allah, there is no might nor power except with Allah.', reference: 'Abu Dawud 4/325', category: 'home', occasion: 'When leaving the home', virtue: 'He is guided, defended, and protected. The devil moves away.', tags: ['home', 'leaving', 'protection'] },
  { id: 143, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ', transliteration: 'Allahumma inni asaluka khayral-mawliji wa khayral-makhraji', translation: 'O Allah, I ask You for the best entrance and the best exit.', reference: 'Abu Dawud 4/325', category: 'home', occasion: 'When entering the home', tags: ['home', 'entering'] },
  { id: 144, arabic: 'اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا وَفِي لِسَانِي نُورًا وَفِي سَمْعِي نُورًا وَفِي بَصَرِي نُورًا', transliteration: 'Allahummaj-al fi qalbi nooran wa fi lisani nooran wa fi sami nooran wa fi basari noora', translation: 'O Allah, place light in my heart, light on my tongue, light in my hearing, and light in my sight.', reference: 'Sahih Bukhari, Muslim', category: 'prayer', occasion: 'When going to the mosque or praying', tags: ['prayer', 'mosque', 'light'] },
  { id: 145, arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ', transliteration: 'Allahummaf-tah li abwaba rahmatik', translation: 'O Allah, open for me the doors of Your mercy.', reference: 'Muslim 1/494', category: 'prayer', occasion: 'When entering the mosque', tags: ['prayer', 'mosque', 'entering'] },
  { id: 146, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ', transliteration: 'Allahumma inni asaluka min fadlik', translation: 'O Allah, I ask You from Your bounty.', reference: 'Muslim 1/494', category: 'prayer', occasion: 'When leaving the mosque', tags: ['prayer', 'mosque', 'leaving'] },
  { id: 147, arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِي ثَمَرِنَا وَبَارِكْ لَنَا فِي مَدِينَتِنَا', transliteration: 'Allahumma barik lana fi thamarina wa barik lana fi madinatina', translation: 'O Allah, bless us in our fruits and bless us in our city.', reference: 'Muslim 2/1000', category: 'home', occasion: 'Dua for barakah in your city/home', tags: ['home', 'barakah', 'city'] },
  { id: 148, arabic: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي وَوَسِّعْ لِي فِي دَارِي وَبَارِكْ لِي فِي رِزْقِي', transliteration: 'Allahummagh-fir li dhanbi wa wassi li fi dari wa barik li fi rizqi', translation: 'O Allah, forgive my sin, make my home spacious, and bless my provision.', reference: 'Tirmidhi, Nasai (Sahih)', category: 'home', occasion: 'Daily — comprehensive home dua', tags: ['home', 'forgiveness', 'rizq', 'barakah'] },
  { id: 149, arabic: 'رَبِّ أَنْزِلْنِي مُنْزَلًا مُبَارَكًا وَأَنْتَ خَيْرُ الْمُنْزِلِينَ', transliteration: 'Rabbi anzilni munzalan mubarakan wa anta khayrul-munzileen', translation: 'My Lord, let me land at a blessed landing place, and You are the best to accommodate.', reference: 'Quran 23:29', category: 'home', occasion: 'When moving to a new home or place', tags: ['home', 'new home', 'quran', 'barakah'] },
  { id: 150, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ جَارِ السُّوءِ', transliteration: 'Allahumma inni aoodhu bika min jaaris-soo', translation: 'O Allah, I seek refuge in You from a bad neighbour.', reference: 'Abu Dawud (Sahih)', category: 'home', occasion: 'When moving to a new neighbourhood', tags: ['home', 'neighbour', 'protection'] },
  // FOOD (151-158)
  { id: 151, arabic: 'بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ', transliteration: 'Bismillahi wa ala barakatillah', translation: 'In the name of Allah and with the blessings of Allah.', reference: 'Abu Dawud, Ibn Majah', category: 'food', occasion: 'Before eating — alternative', tags: ['food', 'eating', 'barakah'] },
  { id: 152, arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ', transliteration: 'Alhamdu lillahil-ladhi atamani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah', translation: 'All praise is for Allah who fed me this and provided it without any might or power from myself.', reference: 'Abu Dawud, Tirmidhi', category: 'food', occasion: 'After eating', virtue: 'All previous sins are forgiven', tags: ['food', 'after eating', 'forgiveness'] },
  { id: 153, arabic: 'اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي', transliteration: 'Allahumma atim man atamani wasqi man saqani', translation: 'O Allah, feed the one who fed me and give drink to the one who gave me drink.', reference: 'Muslim 3/1626', category: 'food', occasion: 'Dua for the host', tags: ['food', 'host', 'gratitude'] },
  { id: 154, arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَأَطْعِمْنَا خَيْرًا مِنْهُ', transliteration: 'Allahumma barik lana fihi wa atimna khayran minhu', translation: 'O Allah, bless it for us and feed us better than it.', reference: 'Abu Dawud, Tirmidhi', category: 'food', occasion: 'After drinking milk', tags: ['food', 'milk', 'barakah'] },
  { id: 155, arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ', transliteration: 'Allahumma barik lana fihi wa zidna minhu', translation: 'O Allah, bless it for us and give us more of it.', reference: 'Tirmidhi', category: 'food', occasion: 'After drinking anything other than milk', tags: ['food', 'drinking'] },
  // HEALTH (156-165)
  { id: 156, arabic: 'بِسْمِ اللَّهِ أَرْقِيكَ مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنِ حَاسِدٍ اللَّهُ يَشْفِيكَ', transliteration: 'Bismillahi arqeeka min kulli shayin yudheeka min sharri kulli nafsin aw aynin hasidin Allahu yashfeek', translation: 'In the name of Allah I perform ruqyah for you, from everything that harms you, from every soul or envious eye. May Allah heal you.', reference: 'Muslim 4/1718', category: 'health', occasion: 'Ruqyah — recite over the sick', tags: ['health', 'ruqyah', 'evil eye'] },
  { id: 157, arabic: 'أَعُوذُ بِعِزَّةِ اللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ', transliteration: 'Aoodhu bi-izzatillahi wa qudratihi min sharri ma ajidu wa uhadhir', translation: 'I seek refuge in the might and power of Allah from the evil of what I feel and fear.', reference: 'Muslim 4/1728', category: 'health', occasion: 'Place hand on pain and say 7 times', tags: ['health', 'pain'] },
  { id: 158, arabic: 'اللَّهُمَّ رَبَّ النَّاسِ مُذْهِبَ الْبَأْسِ اشْفِ أَنْتَ الشَّافِي لَا شَافِيَ إِلَّا أَنْتَ', transliteration: 'Allahumma Rabban-nasi mudhhibal-basi ishfi antash-Shafi la shafiya illa ant', translation: 'O Allah, Lord of mankind, remover of harm, heal — You are the Healer, there is no healer but You.', reference: 'Sahih Bukhari', category: 'health', occasion: 'For healing — alternative wording', tags: ['health', 'healing'] },
  { id: 159, arabic: 'اللَّهُمَّ اشْفِ عَبْدَكَ يَنْكَأُ لَكَ عَدُوًّا أَوْ يَمْشِي لَكَ إِلَى صَلَاةٍ', transliteration: 'Allahummash-fi abdaka yanka laka aduwwan aw yamshi laka ila salah', translation: 'O Allah, heal Your servant who may then fight for Your cause or walk to prayer for Your sake.', reference: 'Abu Dawud (Sahih)', category: 'health', occasion: 'Dua for a sick person to recover', tags: ['health', 'sick', 'recovery'] },
  { id: 160, arabic: 'أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَنِي', transliteration: 'Asalullaha al-Adheema Rabbal-Arshil-Adheemi an yashfiyani', translation: 'I ask Allah the Mighty, Lord of the Mighty Throne, to heal me.', reference: 'Tirmidhi (Sahih)', category: 'health', occasion: 'Say 7 times for yourself when sick', virtue: 'If it is not your time, you will be cured', tags: ['health', 'self', 'healing'] },
  { id: 161, arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي لَا إِلَهَ إِلَّا أَنْتَ', transliteration: 'Allahumma aafini fi badani Allahumma aafini fi sami Allahumma aafini fi basari la ilaha illa ant', translation: 'O Allah, grant health to my body, my hearing, my sight. None has the right to be worshipped except You.', reference: 'Abu Dawud 4/324', category: 'health', occasion: 'Say 3 times morning and evening', tags: ['health', 'morning', 'evening'] },
  { id: 162, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْبَرَصِ وَالْجُنُونِ وَالْجُذَامِ وَسَيِّئِ الْأَسْقَامِ', transliteration: 'Allahumma inni aoodhu bika minal-barasi wal-junooni wal-judhami wa sayyi-il-asqam', translation: 'O Allah, I seek refuge in You from leprosy, madness, elephantiasis, and evil diseases.', reference: 'Abu Dawud (Sahih)', category: 'health', occasion: 'Daily protection from illness', tags: ['health', 'protection', 'disease'] },
  { id: 163, arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ', transliteration: 'Bismillahil-ladhi la yadurru maasmihi shayun fil-ardi wa la fis-samai wa huwas-Samiul-Aleem', translation: 'In the Name of Allah, with whose Name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.', reference: 'Abu Dawud, Tirmidhi', category: 'protection', occasion: 'Say 3 times morning and evening', virtue: 'Nothing will harm him', tags: ['protection', 'morning', 'evening', 'harm'] },
  { id: 164, arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ', transliteration: 'Aoodhu bikalimatillahit-tammaati min sharri ma khalaq', translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created.', reference: 'Muslim 4/2081', category: 'protection', occasion: 'Say 3 times in the evening', virtue: 'Nothing will harm him that night', tags: ['protection', 'evening'] },
  { id: 165, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ زَوَالِ نِعْمَتِكَ وَتَحَوُّلِ عَافِيَتِكَ وَفُجَاءَةِ نِقْمَتِكَ وَجَمِيعِ سَخَطِكَ', transliteration: 'Allahumma inni aoodhu bika min zawali nimatika wa tahawwuli afiyatika wa fujaa-ati niqmatika wa jamee-i sakhatik', translation: 'O Allah, I seek refuge in You from the removal of Your blessing, the change of Your protection, Your sudden punishment, and all of Your displeasure.', reference: 'Muslim 4/2097', category: 'protection', occasion: 'Daily comprehensive protection', tags: ['protection', 'blessings', 'comprehensive'] },
];
