// lib/duaDatabase2.ts
// Extended Dua Database — Additional 150 authentic duas
// Sources: Hisnul Muslim, Sahih Bukhari, Sahih Muslim, Quran

import { type Dua } from './duaDatabase';

export const DUAS_EXTENDED: Dua[] = [
  // PROTECTION (51-65)
  { id: 51, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ مَا عَمِلْتُ وَمِنْ شَرِّ مَا لَمْ أَعْمَلْ', transliteration: 'Allahumma inni aoodhu bika min sharri ma amiltu wa min sharri ma lam amal', translation: 'O Allah, I seek refuge in You from the evil of what I have done and from the evil of what I have not done.', reference: 'Muslim 4/2085', category: 'protection', occasion: 'Morning and evening', tags: ['protection', 'morning', 'evening'] },
  { id: 52, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْبَرَصِ وَالْجُنُونِ وَالْجُذَامِ وَسَيِّئِ الْأَسْقَامِ', transliteration: 'Allahumma inni aoodhu bika minal-barasi wal-junooni wal-judhami wa sayyi-il-asqam', translation: 'O Allah, I seek refuge in You from leprosy, madness, elephantiasis, and evil sicknesses.', reference: 'Abu Dawud 1/57', category: 'protection', occasion: 'Daily protection from illness', tags: ['protection', 'health'] },
  { id: 53, arabic: 'اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي', transliteration: 'Allahummah-fadhni min bayni yadayya wa min khalfi wa an yameeni wa an shimali wa min fawqi', translation: 'O Allah, protect me from my front, behind me, my right, my left, and from above me.', reference: 'Abu Dawud, Ibn Majah', category: 'protection', occasion: 'Morning — complete protection from all directions', tags: ['protection', 'morning', 'comprehensive'] },
  { id: 54, arabic: 'اللَّهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي', transliteration: 'Allahummast-tur awrati wa aamin rawati', translation: 'O Allah, conceal my faults and calm my fears.', reference: 'Abu Dawud 4/324', category: 'protection', occasion: 'Morning and evening', tags: ['protection', 'fear', 'faults'] },
  { id: 55, arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ', transliteration: 'Aoodhu bikalimatillahit-tammati min kulli shaytanin wa hammah wa min kulli aynin lammah', translation: 'I seek refuge in the perfect words of Allah from every devil, poisonous creature, and every evil eye.', reference: 'Sahih Bukhari 4/119', category: 'protection', occasion: 'For protecting children', tags: ['protection', 'children', 'evil eye'] },
  // ANXIETY & DISTRESS (56-75)
  { id: 56, arabic: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ', transliteration: 'La ilaha illa anta subhanaka inni kuntu minaz-dhalimeen', translation: 'None has the right to be worshipped except You. Glory be to You. Indeed, I have been of the wrongdoers.', reference: 'Quran 21:87', category: 'anxiety', occasion: 'Dua of Yunus (AS) — for any difficulty', virtue: 'No Muslim makes this dua except that Allah answers it', tags: ['anxiety', 'distress', 'quran'] },
  { id: 57, arabic: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا', transliteration: 'Allahumma la sahla illa ma jaaltahu sahla wa anta tajalu al-hazna idha shitta sahla', translation: 'O Allah, nothing is easy except what You make easy, and You can make sadness easy if You will.', reference: 'Ibn Hibban (Sahih)', category: 'anxiety', occasion: 'When facing difficulty or sadness', tags: ['anxiety', 'difficulty', 'ease'] },
  { id: 58, arabic: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا', transliteration: 'Inna lillahi wa inna ilayhi rajioon. Allahumma-jurni fi museebati wa akhlif li khayran minha', translation: 'To Allah we belong and to Him we shall return. O Allah, reward me in my calamity and replace it with something better.', reference: 'Muslim 2/632', category: 'anxiety', occasion: 'When struck by a calamity or loss', tags: ['anxiety', 'calamity', 'loss'] },
  { id: 59, arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ', transliteration: 'Hasbunallahu wa nimal wakeel', translation: 'Allah is sufficient for us and He is the best disposer of affairs.', reference: 'Quran 3:173', category: 'anxiety', occasion: 'When overwhelmed or facing enemies', tags: ['anxiety', 'tawakkul', 'quran'] },
  { id: 60, arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ', transliteration: 'Ya Hayyu ya Qayyoomu bi-rahmatika astagheethu', translation: 'O Living, O Self-Sustaining, in Your mercy I seek relief.', reference: 'Tirmidhi (Hasan)', category: 'anxiety', occasion: 'When in extreme distress', tags: ['anxiety', 'distress', 'mercy'] },
  { id: 61, arabic: 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ', transliteration: 'Allahumma rahmataka arju fala takilni ila nafsi tarfata ayn', translation: 'O Allah, it is Your mercy that I hope for, so do not leave me to myself even for a blink of an eye.', reference: 'Abu Dawud 4/324', category: 'anxiety', occasion: 'When feeling helpless', tags: ['anxiety', 'helplessness', 'mercy'] },
  // FORGIVENESS (62-75)
  { id: 62, arabic: 'رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ', transliteration: 'Rabbana dhalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonanna minal-khasireen', translation: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.', reference: 'Quran 7:23', category: 'forgiveness', occasion: 'Seeking forgiveness — dua of Adam (AS)', tags: ['forgiveness', 'quran', 'adam'] },
  { id: 63, arabic: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ', transliteration: 'Rabbighfir li wa tub alayya innaka antat-Tawwabur-Raheem', translation: 'My Lord, forgive me and accept my repentance. You are the Acceptor of Repentance, the Most Merciful.', reference: 'Abu Dawud, Tirmidhi', category: 'forgiveness', occasion: 'General istighfar — say frequently', tags: ['forgiveness', 'repentance'] },
  { id: 64, arabic: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي', transliteration: 'Allahumma innaka Afuwwun tuhibbul afwa fafu anni', translation: 'O Allah, You are Forgiving and love forgiveness, so forgive me.', reference: 'Tirmidhi (Sahih)', category: 'forgiveness', occasion: 'Laylatul Qadr and anytime', tags: ['forgiveness', 'laylatul qadr'] },
  { id: 65, arabic: 'رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا', transliteration: 'Rabbana-ghfir lana dhunubana wa israfana fi amrina wa thabbit aqdamana', translation: 'Our Lord, forgive us our sins and our excesses, and make our feet firm.', reference: 'Quran 3:147', category: 'forgiveness', occasion: 'Seeking forgiveness and steadfastness', tags: ['forgiveness', 'quran', 'steadfastness'] },
  { id: 66, arabic: 'رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا', transliteration: 'Rabbana la tuakhidhna in naseena aw akhtana', translation: 'Our Lord, do not impose blame upon us if we have forgotten or erred.', reference: 'Quran 2:286', category: 'forgiveness', occasion: 'When you make a mistake', tags: ['forgiveness', 'quran', 'mistakes'] },
  { id: 67, arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ', transliteration: 'Astaghfirullaha al-Adheema alladhi la ilaha illa huwal-Hayyul-Qayyoom wa atoobu ilayh', translation: 'I seek forgiveness of Allah the Mighty, whom there is none worthy of worship except Him, the Living, the Sustainer, and I repent to Him.', reference: 'Abu Dawud, Tirmidhi', category: 'forgiveness', occasion: 'After sinning', virtue: 'Allah will forgive him even if he fled from battle', tags: ['forgiveness', 'istighfar'] },
  { id: 68, arabic: 'رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ', transliteration: 'Rabbanagh-fir li wa liwalidayya wa lil-mumineena yawma yaqoomul-hisab', translation: 'Our Lord, forgive me and my parents and the believers the Day the account is established.', reference: 'Quran 14:41', category: 'forgiveness', occasion: 'Dua for parents', tags: ['forgiveness', 'parents', 'quran'] },
  // HEALTH (69-80)
  { id: 69, arabic: 'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِ أَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ', transliteration: 'Allahumma Rabban-nas adhhibil-bas ishfi antash-Shafi la shifaa illa shifauk', translation: 'O Allah, Lord of mankind, remove the illness, cure — You are the One who cures. There is no cure except Your cure.', reference: 'Sahih Bukhari 7/131', category: 'health', occasion: 'For a sick person', tags: ['health', 'healing', 'ruqyah'] },
  { id: 70, arabic: 'أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ', transliteration: 'Asalullaha al-Adheema Rabbal-Arshil-Adheemi an yashfiyak', translation: 'I ask Allah the Mighty, Lord of the Mighty Throne, to cure you.', reference: 'Abu Dawud, Tirmidhi', category: 'health', occasion: 'Say 7 times when visiting a sick person', virtue: 'If it is not his time, he will be cured', tags: ['health', 'visiting sick'] },
  { id: 71, arabic: 'لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ', transliteration: 'La basa tahoorun in shaa Allah', translation: 'No worry, it is a purification, if Allah wills.', reference: 'Sahih Bukhari 7/118', category: 'health', occasion: 'When visiting a sick person', tags: ['health', 'visiting sick', 'comfort'] },
  { id: 72, arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي', transliteration: 'Allahumma aafini fi badani, Allahumma aafini fi sami, Allahumma aafini fi basari', translation: 'O Allah, grant my body health. O Allah, grant my hearing health. O Allah, grant my sight health.', reference: 'Abu Dawud 4/324', category: 'health', occasion: 'Morning and evening — 3 times', tags: ['health', 'morning', 'evening'] },
];
