// lib/duaDatabase5.ts
// Batch 5 — 50 more authentic duas (166-215)

import { type Dua } from './duaDatabase';

export const DUAS_BATCH5: Dua[] = [
  // ANXIETY & DISTRESS — more (166-180)
  { id: 166, arabic: 'اللَّهُمَّ إِنِّي عَبْدُكَ ابْنُ عَبْدِكَ ابْنُ أَمَتِكَ نَاصِيَتِي بِيَدِكَ مَاضٍ فِيَّ حُكْمُكَ عَدْلٌ فِيَّ قَضَاؤُكَ أَسْأَلُكَ بِكُلِّ اسْمٍ هُوَ لَكَ سَمَّيْتَ بِهِ نَفْسَكَ أَنْ تَجْعَلَ الْقُرْآنَ رَبِيعَ قَلْبِي وَنُورَ صَدْرِي وَجَلَاءَ حُزْنِي وَذَهَابَ هَمِّي', transliteration: 'Allahumma inni abduka ibnu abdika ibnu amatika nasiyati biyadika madin fiyya hukmuka adlun fiyya qadauka asaluka bikulli ismin huwa laka sammayta bihi nafsaka an tajal al-Qurana rabee-a qalbi wa noora sadri wa jalaa-a huzni wa dhahaba hammi', translation: 'O Allah, I am Your servant, son of Your servant, son of Your maidservant. My forelock is in Your hand. Your command over me is forever executed and Your decree over me is just. I ask You by every name belonging to You which You have named Yourself with, to make the Quran the spring of my heart, the light of my chest, the departure of my sadness, and the release of my anxiety.', reference: 'Ahmad 1/391 (Sahih)', category: 'anxiety', occasion: 'When feeling sad or depressed — the full dua', virtue: 'No one says this except that Allah removes his sadness and replaces it with joy', tags: ['anxiety', 'sadness', 'depression', 'comprehensive', 'quran'] },
  { id: 167, arabic: 'لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ رَبُّ الْعَرْشِ الْكَرِيمِ', transliteration: 'La ilaha illallahul-Adheemul-Haleem la ilaha illallahu Rabbul-Arshil-Adheem la ilaha illallahu Rabbus-samawati wa Rabbul-ardi Rabbul-Arshil-Kareem', translation: 'None has the right to be worshipped except Allah, the Mighty, the Forbearing. None has the right to be worshipped except Allah, Lord of the Magnificent Throne. None has the right to be worshipped except Allah, Lord of the heavens, Lord of the earth, Lord of the Noble Throne.', reference: 'Sahih Bukhari 8/154, Muslim 4/2092', category: 'anxiety', occasion: 'When in severe distress or calamity', tags: ['anxiety', 'distress', 'calamity'] },
  { id: 168, arabic: 'اللَّهُمَّ اجْعَلْ لِي مِنْ كُلِّ هَمٍّ فَرَجًا وَمِنْ كُلِّ ضِيقٍ مَخْرَجًا', transliteration: 'Allahummaj-al li min kulli hammin farajan wa min kulli deeqin makhraja', translation: 'O Allah, make for me a way out of every worry and a relief from every hardship.', reference: 'Ahmad (Hasan)', category: 'anxiety', occasion: 'When overwhelmed with worries', tags: ['anxiety', 'worry', 'relief'] },
  { id: 169, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ', transliteration: 'Allahumma inni aoodhu bika minal-hammi wal-hazani wal-ajzi wal-kasali wal-bukhli wal-jubni wa dalaid-dayni wa ghalabatir-rijal', translation: 'O Allah, I seek refuge in You from worry, grief, inability, laziness, miserliness, cowardice, the burden of debt, and being overpowered by men.', reference: 'Sahih Bukhari 7/158', category: 'anxiety', occasion: 'Comprehensive protection from all forms of distress', tags: ['anxiety', 'worry', 'debt', 'comprehensive'] },
  { id: 170, arabic: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا', transliteration: 'Allahumma la sahla illa ma jaaltahu sahlan wa anta tajal al-hazna idha shitta sahla', translation: 'O Allah, nothing is easy except what You make easy, and You can make grief easy if You will.', reference: 'Ibn Hibban (Sahih)', category: 'anxiety', occasion: 'Before any difficult task or when grieving', tags: ['anxiety', 'difficulty', 'grief', 'ease'] },
  { id: 171, arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', transliteration: 'Hasbiyallahu la ilaha illa huwa alayhi tawakkaltu wa huwa Rabbul-Arshil-Adheem', translation: 'Allah is sufficient for me. None has the right to be worshipped except Him. I place my trust in Him and He is Lord of the Majestic Throne.', reference: 'Quran 9:129, Abu Dawud', category: 'anxiety', occasion: 'Say 7 times morning and evening', virtue: 'Allah will grant him whatever he desires', tags: ['anxiety', 'tawakkul', 'quran', 'morning', 'evening'] },
  { id: 172, arabic: 'تَوَكَّلْتُ عَلَى اللَّهِ الْحَيِّ الَّذِي لَا يَمُوتُ', transliteration: 'Tawakkaltu alallahil-Hayyil-ladhi la yamoot', translation: 'I place my trust in the Living who does not die.', reference: 'Quran 25:58', category: 'anxiety', occasion: 'When facing any fear or uncertainty', tags: ['anxiety', 'tawakkul', 'quran'] },
  // FORGIVENESS — more (173-185)
  { id: 173, arabic: 'رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِلَّذِينَ آمَنُوا', transliteration: 'Rabbana-ghfir lana wa li-ikhwaninal-ladheena sabaqoona bil-imani wa la tajal fi quloobina ghillan lilladheena amanu', translation: 'Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts resentment toward those who have believed.', reference: 'Quran 59:10', category: 'forgiveness', occasion: 'Dua for all Muslims past and present', tags: ['forgiveness', 'quran', 'ummah', 'brotherhood'] },
  { id: 174, arabic: 'رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي', transliteration: 'Rabbi inni dhalamtu nafsi faghfir li', translation: 'My Lord, indeed I have wronged myself, so forgive me.', reference: 'Quran 28:16', category: 'forgiveness', occasion: 'After committing a sin — dua of Musa (AS)', tags: ['forgiveness', 'quran', 'musa', 'sin'] },
  { id: 175, arabic: 'رَبَّنَا إِنَّنَا سَمِعْنَا مُنَادِيًا يُنَادِي لِلْإِيمَانِ أَنْ آمِنُوا بِرَبِّكُمْ فَآمَنَّا رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا', transliteration: 'Rabbana innana samina munadiyan yunadi lil-imani an aminu bi-Rabbikum fa-amanna Rabbana faghfir lana dhunubana wa kaffir anna sayyiatina', translation: 'Our Lord, indeed we have heard a caller calling to faith saying Believe in your Lord, and we have believed. Our Lord, forgive us our sins and remove from us our misdeeds.', reference: 'Quran 3:193', category: 'forgiveness', occasion: 'Seeking forgiveness after hearing the call of faith', tags: ['forgiveness', 'quran', 'faith'] },
  { id: 176, arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ', transliteration: 'Subhanaka Allahumma wa bihamdika ashhadu an la ilaha illa anta astaghfiruka wa atoobu ilayk', translation: 'Glory is to You O Allah, and praise. I bear witness that none has the right to be worshipped except You. I seek Your forgiveness and turn to You in repentance.', reference: 'Abu Dawud, Tirmidhi (Sahih)', category: 'forgiveness', occasion: 'Kaffaratul Majlis — when leaving any gathering', virtue: 'Expiation for what occurred in that gathering', tags: ['forgiveness', 'gathering', 'kaffarah'] },
  { id: 177, arabic: 'اللَّهُمَّ اغْفِرْ لِي خَطِيئَتِي وَجَهْلِي وَإِسْرَافِي فِي أَمْرِي وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي', transliteration: 'Allahummagh-fir li khateeatee wa jahli wa israfi fi amri wa ma anta alamu bihi minni', translation: 'O Allah, forgive my sins, my ignorance, my excess in my affairs, and what You know better than I.', reference: 'Sahih Bukhari, Muslim', category: 'forgiveness', occasion: 'Comprehensive istighfar', tags: ['forgiveness', 'comprehensive', 'sins'] },
  { id: 178, arabic: 'اللَّهُمَّ اغْفِرْ لِي مَا قَدَّمْتُ وَمَا أَخَّرْتُ وَمَا أَسْرَرْتُ وَمَا أَعْلَنْتُ وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي', transliteration: 'Allahummagh-fir li ma qaddamtu wa ma akhkhartu wa ma asrartu wa ma alantu wa ma anta alamu bihi minni', translation: 'O Allah, forgive me what I have done before and after, what I have hidden and what I have declared, and what You know better than I.', reference: 'Muslim 1/534', category: 'forgiveness', occasion: 'In sujood or after prayer', tags: ['forgiveness', 'comprehensive', 'prayer'] },
  // PROTECTION — more (179-190)
  { id: 179, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا', transliteration: 'Allahumma inni aoodhu bika min sharri nafsi wa min sharri kulli dabbatin anta akhidhun binasiyatiha', translation: 'O Allah, I seek refuge in You from the evil of my own soul and from the evil of every creature that You hold by its forelock.', reference: 'Abu Dawud (Sahih)', category: 'protection', occasion: 'Morning protection', tags: ['protection', 'morning', 'self'] },
  { id: 180, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِوَجْهِكَ الْكَرِيمِ وَكَلِمَاتِكَ التَّامَّاتِ مِنْ شَرِّ مَا أَنْتَ آخِذٌ بِنَاصِيَتِهِ', transliteration: 'Allahumma inni aoodhu biwajhikal-kareemi wa kalimatikattammati min sharri ma anta akhidhun binasiyatih', translation: 'O Allah, I seek refuge in Your Noble Face and Your perfect words from the evil of that which You hold by its forelock.', reference: 'Abu Dawud (Sahih)', category: 'protection', occasion: 'General protection', tags: ['protection', 'comprehensive'] },
  { id: 181, arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ عَلَيْكَ تَوَكَّلْتُ وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ', transliteration: 'Allahumma anta Rabbi la ilaha illa anta alayka tawakkaltu wa anta Rabbul-Arshil-Adheem', translation: 'O Allah, You are my Lord. None has the right to be worshipped except You. In You I place my trust and You are Lord of the Majestic Throne.', reference: 'Ibn Majah (Sahih)', category: 'protection', occasion: 'When feeling afraid or insecure', tags: ['protection', 'fear', 'tawakkul'] },
  { id: 182, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ سَمْعِي وَمِنْ شَرِّ بَصَرِي وَمِنْ شَرِّ لِسَانِي وَمِنْ شَرِّ قَلْبِي', transliteration: 'Allahumma inni aoodhu bika min sharri sami wa min sharri basari wa min sharri lisani wa min sharri qalbi', translation: 'O Allah, I seek refuge in You from the evil of my hearing, my sight, my tongue, and my heart.', reference: 'Abu Dawud, Tirmidhi (Sahih)', category: 'protection', occasion: 'Daily — protection from sins of the senses', tags: ['protection', 'senses', 'daily'] },
  { id: 183, arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكَسَلِ وَالْهَرَمِ وَالْمَأْثَمِ وَالْمَغْرَمِ', transliteration: 'Allahumma inni aoodhu bika minal-kasali wal-harami wal-mathami wal-maghrami', translation: 'O Allah, I seek refuge in You from laziness, old age, sin, and debt.', reference: 'Sahih Bukhari', category: 'protection', occasion: 'Daily protection', tags: ['protection', 'laziness', 'debt', 'sin'] },
  // RIZQ & PROVISION — more (184-195)
  { id: 184, arabic: 'اللَّهُمَّ أَغْنِنِي بِالْعِلْمِ وَزَيِّنِّي بِالْحِلْمِ وَأَكْرِمْنِي بِالتَّقْوَى وَجَمِّلْنِي بِالْعَافِيَةِ', transliteration: 'Allahumma aghnini bil-ilmi wa zayyinni bil-hilmi wa akrimni bit-taqwa wa jammilni bil-afiyah', translation: 'O Allah, enrich me with knowledge, adorn me with forbearance, honour me with piety, and beautify me with well-being.', reference: 'Tabarani (Hasan)', category: 'rizq', occasion: 'Comprehensive dua for inner and outer wealth', tags: ['rizq', 'knowledge', 'character'] },
  { id: 185, arabic: 'اللَّهُمَّ ارْزُقْنِي رِزْقًا حَلَالًا طَيِّبًا بِغَيْرِ كَدٍّ وَاسْتَجِبْ دُعَائِي بِغَيْرِ رَدٍّ', transliteration: 'Allahummar-zuqni rizqan halalan tayyiban bi-ghayri kaddin wastajib duaai bi-ghayri radd', translation: 'O Allah, provide me with halal and good provision without hardship, and answer my dua without rejection.', reference: 'Tabarani', category: 'rizq', occasion: 'When seeking halal provision', tags: ['rizq', 'halal', 'provision'] },
  { id: 186, arabic: 'اللَّهُمَّ اقْضِ عَنِّي الدَّيْنَ وَأَغْنِنِي مِنَ الْفَقْرِ', transliteration: 'Allahumma-qdhi annid-dayna wa aghnini minal-faqr', translation: 'O Allah, settle my debt and enrich me from poverty.', reference: 'Tabarani (Hasan)', category: 'rizq', occasion: 'When in debt', tags: ['rizq', 'debt'] },
  { id: 187, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ وَرَحْمَتِكَ فَإِنَّهُ لَا يَمْلِكُهَا إِلَّا أَنْتَ', transliteration: 'Allahumma inni asaluka min fadlika wa rahmatika fa-innahu la yamlikuha illa ant', translation: 'O Allah, I ask You from Your bounty and mercy, for none possesses them except You.', reference: 'Tabarani (Sahih)', category: 'rizq', occasion: 'When asking Allah for provision', tags: ['rizq', 'mercy', 'bounty'] },
  // LIFE EVENTS — more (188-200)
  { id: 188, arabic: 'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا', transliteration: 'Allahumma allif bayna quloobina wa aslih dhata baynina', translation: 'O Allah, unite our hearts and rectify our mutual relations.', reference: 'Abu Dawud (Sahih)', category: 'life', occasion: 'For family harmony or resolving disputes', tags: ['life', 'family', 'unity', 'harmony'] },
  { id: 189, arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الثَّبَاتَ فِي الْأَمْرِ وَالْعَزِيمَةَ عَلَى الرُّشْدِ', transliteration: 'Allahumma inni asalukat-thabata fil-amri wal-azeemata alar-rushd', translation: 'O Allah, I ask You for steadfastness in my affairs and determination upon guidance.', reference: 'Ahmad, Nasai (Sahih)', category: 'life', occasion: 'When making important life decisions', tags: ['life', 'decisions', 'steadfastness'] },
  { id: 190, arabic: 'اللَّهُمَّ خِرْ لِي وَاخْتَرْ لِي', transliteration: 'Allahumma khir li wakhtir li', translation: 'O Allah, choose for me and select for me.', reference: 'Tirmidhi (Hasan)', category: 'life', occasion: 'When unsure about a decision', tags: ['life', 'decisions', 'istikhara'] },
  { id: 191, arabic: 'رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', transliteration: 'Rabbana atmim lana noorana waghfir lana innaka ala kulli shayin qadeer', translation: 'Our Lord, perfect for us our light and forgive us. Indeed, You are over all things capable.', reference: 'Quran 66:8', category: 'forgiveness', occasion: 'Seeking light and forgiveness', tags: ['forgiveness', 'quran', 'light'] },
  { id: 192, arabic: 'رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ', transliteration: 'Rabbi hab li hukman wa alhiqni bis-saliheen', translation: 'My Lord, grant me wisdom and join me with the righteous.', reference: 'Quran 26:83', category: 'knowledge', occasion: 'Dua for wisdom — dua of Ibrahim (AS)', tags: ['knowledge', 'wisdom', 'quran', 'ibrahim'] },
  { id: 193, arabic: 'رَبِّ نَجِّنِي مِنَ الْقَوْمِ الظَّالِمِينَ', transliteration: 'Rabbi najjini minal-qawmidh-dhalimeen', translation: 'My Lord, save me from the wrongdoing people.', reference: 'Quran 28:21', category: 'protection', occasion: 'When facing oppression — dua of Musa (AS)', tags: ['protection', 'oppression', 'quran', 'musa'] },
  { id: 194, arabic: 'رَبِّ لَا تَذَرْ عَلَى الْأَرْضِ مِنَ الْكَافِرِينَ دَيَّارًا', transliteration: 'Rabbi la tadhar alal-ardi minal-kafireena dayyara', translation: 'My Lord, do not leave upon the earth from among the disbelievers an inhabitant.', reference: 'Quran 71:26', category: 'prayer', occasion: 'Dua of Nuh (AS) — for the triumph of truth', tags: ['prayer', 'quran', 'nuh'] },
  { id: 195, arabic: 'رَبِّ ابْنِ لِي عِنْدَكَ بَيْتًا فِي الْجَنَّةِ', transliteration: 'Rabib-ni li indaka baytan fil-jannah', translation: 'My Lord, build for me near You a house in Paradise.', reference: 'Quran 66:11', category: 'prayer', occasion: 'Dua for Paradise — dua of wife of Pharaoh', tags: ['prayer', 'paradise', 'quran'] },
  // EVENTS — more (196-205)
  { id: 196, arabic: 'اللَّهُمَّ بَلِّغْنَا رَمَضَانَ', transliteration: 'Allahumma ballighna Ramadan', translation: 'O Allah, let us reach Ramadan.', reference: 'Ahmad, Tabarani (Hasan)', category: 'events', occasion: 'Before Ramadan — from Rajab/Shaban', tags: ['events', 'ramadan'] },
  { id: 197, arabic: 'اللَّهُمَّ إِنِّي لَكَ صُمْتُ وَبِكَ آمَنْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ', transliteration: 'Allahumma inni laka sumtu wa bika aamantu wa ala rizqika aftartu', translation: 'O Allah, I fasted for You, believed in You, and break my fast with Your provision.', reference: 'Abu Dawud (Mursal — widely used)', category: 'events', occasion: 'When breaking fast — alternative', tags: ['events', 'ramadan', 'iftar'] },
  { id: 198, arabic: 'اللَّهُمَّ تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ', transliteration: 'Allahumma taqabbal minna innaka antas-Sameeul-Aleem wa tub alayna innaka antat-Tawwabur-Raheem', translation: 'O Allah, accept from us. You are the All-Hearing, All-Knowing. And accept our repentance. You are the Acceptor of Repentance, Most Merciful.', reference: 'Quran 2:127-128', category: 'events', occasion: 'After completing any act of worship', tags: ['events', 'acceptance', 'quran'] },
  { id: 199, arabic: 'تَقَبَّلَ اللَّهُ مِنَّا وَمِنْكُمْ', transliteration: 'Taqabbalallahu minna wa minkum', translation: 'May Allah accept from us and from you.', reference: 'Ahmad (Sahih)', category: 'events', occasion: 'Eid greeting — say to each other on Eid', tags: ['events', 'eid', 'greeting'] },
  { id: 200, arabic: 'اللَّهُمَّ اجْعَلْنَا مِنْ عُتَقَائِكَ مِنَ النَّارِ', transliteration: 'Allahummaj-alna min utaqaaika minan-nar', translation: 'O Allah, make us among those You free from the Fire.', reference: 'Tirmidhi (Hasan)', category: 'events', occasion: 'During Ramadan — especially last 10 nights', tags: ['events', 'ramadan', 'fire', 'freedom'] },
  // COMPREHENSIVE QURAN DUAS (201-215)
  { id: 201, arabic: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ', transliteration: 'Rabbana taqabbal minna innaka antas-Sameeul-Aleem', translation: 'Our Lord, accept from us. Indeed You are the All-Hearing, the All-Knowing.', reference: 'Quran 2:127', category: 'prayer', occasion: 'After any good deed', tags: ['quran', 'acceptance'] },
  { id: 202, arabic: 'رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِنْ ذُرِّيَّتِنَا أُمَّةً مُسْلِمَةً لَكَ', transliteration: 'Rabbana wajalna muslimayni laka wa min dhurriyyatina ummatan muslimatan lak', translation: 'Our Lord, make us Muslims submitting to You and from our descendants a Muslim nation submitting to You.', reference: 'Quran 2:128', category: 'home', occasion: 'Dua for Muslim offspring — dua of Ibrahim (AS)', tags: ['quran', 'children', 'islam', 'ibrahim'] },
  { id: 203, arabic: 'رَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا', transliteration: 'Rabbana atina min ladunka rahmatan wa hayyi lana min amrina rashada', translation: 'Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.', reference: 'Quran 18:10', category: 'anxiety', occasion: 'Dua of the People of the Cave — when seeking refuge', tags: ['quran', 'mercy', 'guidance', 'cave'] },
  { id: 204, arabic: 'رَبِّ إِنِّي أَعُوذُ بِكَ أَنْ أَسْأَلَكَ مَا لَيْسَ لِي بِهِ عِلْمٌ', transliteration: 'Rabbi inni aoodhu bika an asalaka ma laysa li bihi ilm', translation: 'My Lord, I seek refuge in You from asking You that of which I have no knowledge.', reference: 'Quran 11:47', category: 'knowledge', occasion: 'Dua of Nuh (AS) — humility before Allah', tags: ['quran', 'knowledge', 'humility', 'nuh'] },
  { id: 205, arabic: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', transliteration: 'Rabbigh-fir warham wa anta khayrur-rahimeen', translation: 'My Lord, forgive and have mercy, and You are the best of the merciful.', reference: 'Quran 23:118', category: 'forgiveness', occasion: 'Short comprehensive dua for mercy', tags: ['quran', 'forgiveness', 'mercy', 'short'] },
  { id: 206, arabic: 'رَبِّ أَعُوذُ بِكَ مِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَعُوذُ بِكَ رَبِّ أَنْ يَحْضُرُونِ', transliteration: 'Rabbi aoodhu bika min hamazatish-shayateeni wa aoodhu bika Rabbi an yahdurun', translation: 'My Lord, I seek refuge in You from the incitements of the devils, and I seek refuge in You, my Lord, lest they be present with me.', reference: 'Quran 23:97-98', category: 'protection', occasion: 'Protection from Shaytan', tags: ['quran', 'protection', 'shaytan'] },
  { id: 207, arabic: 'رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَى وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ وَأَدْخِلْنِي بِرَحْمَتِكَ فِي عِبَادِكَ الصَّالِحِينَ', transliteration: 'Rabbi awzini an ashkura nimataka allati anamta alayya wa ala walidayya wa an amala salihan tardahu wa adkhilni birahmatika fi ibaadikas-saliheen', translation: 'My Lord, enable me to be grateful for Your favour upon me and my parents, to do righteousness that pleases You, and admit me by Your mercy among Your righteous servants.', reference: 'Quran 27:19', category: 'home', occasion: 'Dua of Sulayman (AS) — gratitude and righteousness', tags: ['quran', 'gratitude', 'parents', 'sulayman'] },
  { id: 208, arabic: 'رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ', transliteration: 'Rabbi hab li minas-saliheen', translation: 'My Lord, grant me righteous offspring.', reference: 'Quran 37:100', category: 'life', occasion: 'Dua for righteous children — dua of Ibrahim (AS)', tags: ['quran', 'children', 'righteous', 'ibrahim'] },
  { id: 209, arabic: 'رَبَّنَا اصْرِفْ عَنَّا عَذَابَ جَهَنَّمَ إِنَّ عَذَابَهَا كَانَ غَرَامًا', transliteration: 'Rabbanas-rif anna adhaba jahannama inna adhabaha kana gharama', translation: 'Our Lord, avert from us the punishment of Hell. Indeed, its punishment is ever adhering.', reference: 'Quran 25:65', category: 'protection', occasion: 'Seeking protection from Hell', tags: ['quran', 'fire', 'hell'] },
  { id: 210, arabic: 'رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', transliteration: 'Rabbana atmim lana noorana waghfir lana innaka ala kulli shayin qadeer', translation: 'Our Lord, perfect for us our light and forgive us. Indeed, You are over all things capable.', reference: 'Quran 66:8', category: 'prayer', occasion: 'Dua for light on the Day of Judgement', tags: ['quran', 'light', 'judgement'] },
  { id: 211, arabic: 'رَبِّ اجْعَلْ هَذَا الْبَلَدَ آمِنًا وَاجْنُبْنِي وَبَنِيَّ أَنْ نَعْبُدَ الْأَصْنَامَ', transliteration: 'Rabbij-al hadhal-balada aminan wajnubni wa baniyya an nabuda al-asnam', translation: 'My Lord, make this city secure and keep me and my sons away from worshipping idols.', reference: 'Quran 14:35', category: 'home', occasion: 'Dua for safety of your city — dua of Ibrahim (AS)', tags: ['quran', 'safety', 'city', 'ibrahim'] },
  { id: 212, arabic: 'رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَحْمَةً وَعِلْمًا فَاغْفِرْ لِلَّذِينَ تَابُوا وَاتَّبَعُوا سَبِيلَكَ وَقِهِمْ عَذَابَ الْجَحِيمِ', transliteration: 'Rabbana wasita kulla shayin rahmatan wa ilman faghfir lilladheena tabu wattabau sabeelaka wa qihim adhabal-jaheem', translation: 'Our Lord, You have encompassed all things in mercy and knowledge, so forgive those who have repented and followed Your way and protect them from the punishment of Hellfire.', reference: 'Quran 40:7', category: 'forgiveness', occasion: 'Dua of the angels for believers', tags: ['quran', 'forgiveness', 'angels', 'repentance'] },
  { id: 213, arabic: 'رَبَّنَا وَأَدْخِلْهُمْ جَنَّاتِ عَدْنٍ الَّتِي وَعَدْتَهُمْ وَمَنْ صَلَحَ مِنْ آبَائِهِمْ وَأَزْوَاجِهِمْ وَذُرِّيَّاتِهِمْ', transliteration: 'Rabbana wa adkhilhum jannati adninil-lati waadtahum wa man salaha min abaihim wa azwajihim wa dhurriyyatihim', translation: 'Our Lord, admit them to gardens of perpetual residence which You have promised them and whoever was righteous among their fathers, spouses, and offspring.', reference: 'Quran 40:8', category: 'life', occasion: 'Dua for family to enter Paradise together', tags: ['quran', 'paradise', 'family'] },
  { id: 214, arabic: 'رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ', transliteration: 'Rabbi inni lima anzalta ilayya min khayrin faqeer', translation: 'My Lord, indeed I am, for whatever good You would send down to me, in need.', reference: 'Quran 28:24', category: 'rizq', occasion: 'When in need of anything — dua of Musa (AS)', tags: ['quran', 'need', 'musa', 'rizq'] },
  { id: 215, arabic: 'رَبِّ إِنِّي مَسَّنِيَ الضُّرُّ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ', transliteration: 'Rabbi inni massaniyad-durru wa anta arhamur-rahimeen', translation: 'My Lord, indeed adversity has touched me, and You are the Most Merciful of the merciful.', reference: 'Quran 21:83', category: 'health', occasion: 'When afflicted with illness or hardship — dua of Ayyub (AS)', virtue: 'Allah answered Ayyub and removed his affliction', tags: ['quran', 'health', 'hardship', 'ayyub'] },
];
