// lib/halalDatabaseExtended.ts
// Extended Halal Database — Additional 500+ common food ingredients
// These are all clearly HALAL ingredients commonly found on food labels

import { type Ingredient } from './halalDatabase';

export const extendedHalalIngredients: Record<string, Ingredient> = {

  // ═══════════════════════════════════════════════════════════════════
  // VITAMINS & MINERALS
  // ═══════════════════════════════════════════════════════════════════
  'vitamin a': { name: 'Vitamin A', status: 'halal', reason: 'Synthetic or plant-derived vitamin', category: 'Vitamin' },
  'vitamin b1': { name: 'Vitamin B1 (Thiamine)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'vitamin b2': { name: 'Vitamin B2 (Riboflavin)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'vitamin b3': { name: 'Vitamin B3 (Niacin)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'vitamin b5': { name: 'Vitamin B5 (Pantothenic Acid)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'vitamin b6': { name: 'Vitamin B6 (Pyridoxine)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'vitamin b7': { name: 'Vitamin B7 (Biotin)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'vitamin b9': { name: 'Vitamin B9 (Folic Acid)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'vitamin b12': { name: 'Vitamin B12 (Cobalamin)', status: 'halal', reason: 'Synthetic or fermentation-derived', category: 'Vitamin' },
  'vitamin c': { name: 'Vitamin C (Ascorbic Acid)', status: 'halal', reason: 'Synthetic or plant-derived', category: 'Vitamin' },
  'vitamin d': { name: 'Vitamin D', status: 'halal', reason: 'Synthetic or plant-derived', category: 'Vitamin' },
  'vitamin d2': { name: 'Vitamin D2 (Ergocalciferol)', status: 'halal', reason: 'From yeast/mushrooms', category: 'Vitamin' },
  'vitamin d3': { name: 'Vitamin D3 (Cholecalciferol)', status: 'halal', reason: 'Usually from lanolin (sheep wool) — halal', category: 'Vitamin' },
  'vitamin e': { name: 'Vitamin E (Tocopherol)', status: 'halal', reason: 'Plant-derived antioxidant', category: 'Vitamin' },
  'vitamin k': { name: 'Vitamin K', status: 'halal', reason: 'Synthetic or plant-derived', category: 'Vitamin' },
  'thiamine': { name: 'Thiamine (Vitamin B1)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'riboflavin': { name: 'Riboflavin (Vitamin B2)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'niacin': { name: 'Niacin (Vitamin B3)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'niacinamide': { name: 'Niacinamide', status: 'halal', reason: 'Synthetic form of Vitamin B3', category: 'Vitamin' },
  'pantothenic acid': { name: 'Pantothenic Acid (B5)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'pyridoxine': { name: 'Pyridoxine (Vitamin B6)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'folic acid': { name: 'Folic Acid (Vitamin B9)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'folate': { name: 'Folate', status: 'halal', reason: 'Natural or synthetic B vitamin', category: 'Vitamin' },
  'biotin': { name: 'Biotin (Vitamin B7)', status: 'halal', reason: 'Synthetic vitamin', category: 'Vitamin' },
  'cobalamin': { name: 'Cobalamin (Vitamin B12)', status: 'halal', reason: 'Fermentation-derived', category: 'Vitamin' },
  'retinol': { name: 'Retinol (Vitamin A)', status: 'halal', reason: 'Synthetic vitamin A', category: 'Vitamin' },
  'beta carotene': { name: 'Beta-Carotene', status: 'halal', reason: 'Plant-derived provitamin A', category: 'Vitamin' },
  'ascorbic acid': { name: 'Ascorbic Acid (Vitamin C)', status: 'halal', reason: 'Synthetic or plant-derived', category: 'Vitamin' },
  'tocopherol': { name: 'Tocopherol (Vitamin E)', status: 'halal', reason: 'Plant-derived antioxidant', category: 'Vitamin' },
  'alpha tocopherol': { name: 'Alpha-Tocopherol', status: 'halal', reason: 'Vitamin E — plant-derived', category: 'Vitamin' },
  'calcium': { name: 'Calcium', status: 'halal', reason: 'Mineral nutrient', category: 'Mineral' },
  'sodium': { name: 'Sodium', status: 'halal', reason: 'Mineral element', category: 'Mineral' },
  'potassium': { name: 'Potassium', status: 'halal', reason: 'Mineral element', category: 'Mineral' },
  'phosphorus': { name: 'Phosphorus', status: 'halal', reason: 'Mineral element', category: 'Mineral' },
  'selenium': { name: 'Selenium', status: 'halal', reason: 'Mineral element', category: 'Mineral' },
  'chromium': { name: 'Chromium', status: 'halal', reason: 'Mineral element', category: 'Mineral' },
  'manganese': { name: 'Manganese', status: 'halal', reason: 'Mineral element', category: 'Mineral' },
  'copper': { name: 'Copper', status: 'halal', reason: 'Mineral element', category: 'Mineral' },
  'iodine': { name: 'Iodine', status: 'halal', reason: 'Mineral element', category: 'Mineral' },

  // ═══════════════════════════════════════════════════════════════════
  // ACIDS, SALTS & CHEMICAL COMPOUNDS
  // ═══════════════════════════════════════════════════════════════════
  'citric acid': { name: 'Citric Acid', status: 'halal', reason: 'From citrus fruits or fermentation', category: 'Acid' },
  'lactic acid': { name: 'Lactic Acid', status: 'halal', reason: 'From fermentation of sugars', category: 'Acid' },
  'malic acid': { name: 'Malic Acid', status: 'halal', reason: 'From apples or synthetic', category: 'Acid' },
  'tartaric acid': { name: 'Tartaric Acid', status: 'halal', reason: 'From grapes or synthetic', category: 'Acid' },
  'fumaric acid': { name: 'Fumaric Acid', status: 'halal', reason: 'Synthetic organic acid', category: 'Acid' },
  'acetic acid': { name: 'Acetic Acid', status: 'halal', reason: 'Vinegar base — halal', category: 'Acid' },
  'phosphoric acid': { name: 'Phosphoric Acid', status: 'halal', reason: 'Mineral acid used in soft drinks', category: 'Acid' },
  'sorbic acid': { name: 'Sorbic Acid', status: 'halal', reason: 'Synthetic preservative', category: 'Acid' },
  'benzoic acid': { name: 'Benzoic Acid', status: 'halal', reason: 'Synthetic preservative', category: 'Acid' },
  'propionic acid': { name: 'Propionic Acid', status: 'halal', reason: 'Synthetic preservative', category: 'Acid' },
  'adipic acid': { name: 'Adipic Acid', status: 'halal', reason: 'Synthetic organic acid', category: 'Acid' },
  'gluconic acid': { name: 'Gluconic Acid', status: 'halal', reason: 'From glucose fermentation', category: 'Acid' },
  'sodium citrate': { name: 'Sodium Citrate', status: 'halal', reason: 'Salt of citric acid', category: 'Salt' },
  'potassium citrate': { name: 'Potassium Citrate', status: 'halal', reason: 'Salt of citric acid', category: 'Salt' },
  'calcium citrate': { name: 'Calcium Citrate', status: 'halal', reason: 'Salt of citric acid', category: 'Salt' },
  'sodium bicarbonate': { name: 'Sodium Bicarbonate (Baking Soda)', status: 'halal', reason: 'Mineral compound', category: 'Raising Agent' },
  'baking soda': { name: 'Baking Soda', status: 'halal', reason: 'Sodium bicarbonate — mineral', category: 'Raising Agent' },
  'baking powder': { name: 'Baking Powder', status: 'halal', reason: 'Mixture of bicarbonate and acid — mineral/plant', category: 'Raising Agent' },
  'cream of tartar': { name: 'Cream of Tartar', status: 'halal', reason: 'Potassium bitartrate from grapes', category: 'Acid Salt' },
  'sodium benzoate': { name: 'Sodium Benzoate', status: 'halal', reason: 'Synthetic preservative', category: 'Preservative' },
  'potassium sorbate': { name: 'Potassium Sorbate', status: 'halal', reason: 'Synthetic preservative', category: 'Preservative' },
  'calcium propionate': { name: 'Calcium Propionate', status: 'halal', reason: 'Synthetic bread preservative', category: 'Preservative' },
  'sodium metabisulphite': { name: 'Sodium Metabisulphite', status: 'halal', reason: 'Mineral-derived preservative', category: 'Preservative' },
  'potassium metabisulphite': { name: 'Potassium Metabisulphite', status: 'halal', reason: 'Mineral-derived preservative', category: 'Preservative' },
  'sodium nitrite': { name: 'Sodium Nitrite', status: 'halal', reason: 'Mineral salt preservative', category: 'Preservative' },
  'sodium nitrate': { name: 'Sodium Nitrate', status: 'halal', reason: 'Mineral salt preservative', category: 'Preservative' },
  'calcium chloride': { name: 'Calcium Chloride', status: 'halal', reason: 'Mineral salt', category: 'Mineral Salt' },
  'sodium chloride': { name: 'Sodium Chloride (Salt)', status: 'halal', reason: 'Common table salt', category: 'Mineral Salt' },
  'potassium chloride': { name: 'Potassium Chloride', status: 'halal', reason: 'Mineral salt substitute', category: 'Mineral Salt' },
  'calcium sulphate': { name: 'Calcium Sulphate', status: 'halal', reason: 'Mineral (gypsum)', category: 'Mineral Salt' },
  'magnesium carbonate': { name: 'Magnesium Carbonate', status: 'halal', reason: 'Mineral compound', category: 'Mineral' },
  'silicon dioxide': { name: 'Silicon Dioxide', status: 'halal', reason: 'Mineral anti-caking agent', category: 'Anti-caking' },
  'titanium dioxide': { name: 'Titanium Dioxide', status: 'halal', reason: 'Mineral white pigment', category: 'Colour' },
  'sodium hydroxide': { name: 'Sodium Hydroxide', status: 'halal', reason: 'Mineral-derived alkali', category: 'Processing Aid' },
  'ammonium bicarbonate': { name: 'Ammonium Bicarbonate', status: 'halal', reason: 'Synthetic raising agent', category: 'Raising Agent' },
  'sodium carbonate': { name: 'Sodium Carbonate', status: 'halal', reason: 'Mineral compound (washing soda)', category: 'Processing Aid' },
  'calcium hydroxide': { name: 'Calcium Hydroxide', status: 'halal', reason: 'Mineral compound (slaked lime)', category: 'Processing Aid' },
  'ferrous sulphate': { name: 'Ferrous Sulphate', status: 'halal', reason: 'Iron supplement — mineral', category: 'Mineral' },
  'ferrous fumarate': { name: 'Ferrous Fumarate', status: 'halal', reason: 'Iron supplement — mineral', category: 'Mineral' },
  'zinc oxide': { name: 'Zinc Oxide', status: 'halal', reason: 'Mineral compound', category: 'Mineral' },
  'zinc sulphate': { name: 'Zinc Sulphate', status: 'halal', reason: 'Mineral compound', category: 'Mineral' },

  // ═══════════════════════════════════════════════════════════════════
  // THICKENERS, GUMS & STABILISERS
  // ═══════════════════════════════════════════════════════════════════
  'xanthan gum': { name: 'Xanthan Gum', status: 'halal', reason: 'Produced by bacterial fermentation', category: 'Thickener' },
  'guar gum': { name: 'Guar Gum', status: 'halal', reason: 'From guar bean plant', category: 'Thickener' },
  'gum arabic': { name: 'Gum Arabic', status: 'halal', reason: 'From acacia tree sap', category: 'Thickener' },
  'acacia gum': { name: 'Acacia Gum', status: 'halal', reason: 'From acacia tree sap', category: 'Thickener' },
  'locust bean gum': { name: 'Locust Bean Gum', status: 'halal', reason: 'From carob tree seeds', category: 'Thickener' },
  'carob bean gum': { name: 'Carob Bean Gum', status: 'halal', reason: 'From carob tree seeds', category: 'Thickener' },
  'carrageenan': { name: 'Carrageenan', status: 'halal', reason: 'From red seaweed', category: 'Thickener' },
  'agar': { name: 'Agar', status: 'halal', reason: 'From seaweed — halal gelatin alternative', category: 'Thickener' },
  'agar agar': { name: 'Agar Agar', status: 'halal', reason: 'From seaweed — halal gelatin alternative', category: 'Thickener' },
  'pectin': { name: 'Pectin', status: 'halal', reason: 'From fruit (apple/citrus peel)', category: 'Thickener' },
  'cellulose': { name: 'Cellulose', status: 'halal', reason: 'Plant fibre (wood pulp or cotton)', category: 'Thickener' },
  'methyl cellulose': { name: 'Methyl Cellulose', status: 'halal', reason: 'Modified plant cellulose', category: 'Thickener' },
  'carboxymethyl cellulose': { name: 'Carboxymethyl Cellulose (CMC)', status: 'halal', reason: 'Modified plant cellulose', category: 'Thickener' },
  'hydroxypropyl cellulose': { name: 'Hydroxypropyl Cellulose', status: 'halal', reason: 'Modified plant cellulose', category: 'Thickener' },
  'alginate': { name: 'Alginate', status: 'halal', reason: 'From brown seaweed', category: 'Thickener' },
  'sodium alginate': { name: 'Sodium Alginate', status: 'halal', reason: 'From brown seaweed', category: 'Thickener' },
  'gellan gum': { name: 'Gellan Gum', status: 'halal', reason: 'Produced by bacterial fermentation', category: 'Thickener' },
  'tara gum': { name: 'Tara Gum', status: 'halal', reason: 'From tara tree seeds', category: 'Thickener' },
  'konjac': { name: 'Konjac', status: 'halal', reason: 'From konjac plant root', category: 'Thickener' },
  'glucomannan': { name: 'Glucomannan', status: 'halal', reason: 'From konjac root fibre', category: 'Thickener' },
  'psyllium': { name: 'Psyllium', status: 'halal', reason: 'Plant seed husk fibre', category: 'Fibre' },
  'inulin': { name: 'Inulin', status: 'halal', reason: 'Plant fibre from chicory root', category: 'Fibre' },
  'polydextrose': { name: 'Polydextrose', status: 'halal', reason: 'Synthetic soluble fibre', category: 'Fibre' },

  // ═══════════════════════════════════════════════════════════════════
  // EMULSIFIERS & LECITHINS (HALAL)
  // ═══════════════════════════════════════════════════════════════════
  'soy lecithin': { name: 'Soy Lecithin', status: 'halal', reason: 'From soybeans — plant-derived', category: 'Emulsifier' },
  'sunflower lecithin': { name: 'Sunflower Lecithin', status: 'halal', reason: 'From sunflower seeds — plant-derived', category: 'Emulsifier' },
  'rapeseed lecithin': { name: 'Rapeseed Lecithin', status: 'halal', reason: 'From rapeseed — plant-derived', category: 'Emulsifier' },
  'mono and diglycerides': { name: 'Mono and Diglycerides', status: 'mashbooh', reason: 'Can be from animal fat or vegetable oil — source must be verified', category: 'Emulsifier' },
  'polyglycerol polyricinoleate': { name: 'PGPR', status: 'halal', reason: 'From castor oil — plant-derived', category: 'Emulsifier' },
  'sodium stearoyl lactylate': { name: 'Sodium Stearoyl Lactylate (SSL)', status: 'halal', reason: 'Typically from vegetable stearic acid', category: 'Emulsifier' },
  'calcium stearoyl lactylate': { name: 'Calcium Stearoyl Lactylate (CSL)', status: 'halal', reason: 'Typically from vegetable stearic acid', category: 'Emulsifier' },

  // ═══════════════════════════════════════════════════════════════════
  // FLAVOURINGS & EXTRACTS
  // ═══════════════════════════════════════════════════════════════════
  'vanilla': { name: 'Vanilla', status: 'halal', reason: 'Plant-derived flavouring from vanilla bean', category: 'Flavouring' },
  'vanillin': { name: 'Vanillin', status: 'halal', reason: 'Synthetic vanilla flavour compound', category: 'Flavouring' },
  'cinnamon': { name: 'Cinnamon', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'turmeric': { name: 'Turmeric', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'cumin': { name: 'Cumin', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'coriander': { name: 'Coriander', status: 'halal', reason: 'Plant-derived herb/spice', category: 'Spice' },
  'ginger': { name: 'Ginger', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'nutmeg': { name: 'Nutmeg', status: 'halal', reason: 'Plant-derived spice — halal in food quantities', category: 'Spice' },
  'cardamom': { name: 'Cardamom', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'clove': { name: 'Clove', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'oregano': { name: 'Oregano', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'basil': { name: 'Basil', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'thyme': { name: 'Thyme', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'rosemary': { name: 'Rosemary', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'parsley': { name: 'Parsley', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'mint': { name: 'Mint', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'dill': { name: 'Dill', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'bay leaf': { name: 'Bay Leaf', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'sage': { name: 'Sage', status: 'halal', reason: 'Plant-derived herb', category: 'Herb' },
  'fennel': { name: 'Fennel', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'anise': { name: 'Anise', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'star anise': { name: 'Star Anise', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'mustard': { name: 'Mustard', status: 'halal', reason: 'Plant-derived condiment/spice', category: 'Condiment' },
  'wasabi': { name: 'Wasabi', status: 'halal', reason: 'Plant-derived condiment', category: 'Condiment' },
  'saffron': { name: 'Saffron', status: 'halal', reason: 'Plant-derived spice from crocus flower', category: 'Spice' },
  'chili': { name: 'Chili', status: 'halal', reason: 'Plant-derived spice', category: 'Spice' },
  'paprika': { name: 'Paprika', status: 'halal', reason: 'Plant-derived spice from peppers', category: 'Spice' },
  'cayenne': { name: 'Cayenne', status: 'halal', reason: 'Plant-derived hot pepper spice', category: 'Spice' },

  // ═══════════════════════════════════════════════════════════════════
  // VEGETABLES, FRUITS & PLANT INGREDIENTS
  // ═══════════════════════════════════════════════════════════════════
  'potato': { name: 'Potato', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'carrot': { name: 'Carrot', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'celery': { name: 'Celery', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'spinach': { name: 'Spinach', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'broccoli': { name: 'Broccoli', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'peas': { name: 'Peas', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'corn': { name: 'Corn', status: 'halal', reason: 'Plant-derived grain/vegetable', category: 'Vegetable' },
  'mushroom': { name: 'Mushroom', status: 'halal', reason: 'Fungus — halal', category: 'Vegetable' },
  'bell pepper': { name: 'Bell Pepper', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'cucumber': { name: 'Cucumber', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'lettuce': { name: 'Lettuce', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'cabbage': { name: 'Cabbage', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'cauliflower': { name: 'Cauliflower', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'zucchini': { name: 'Zucchini', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'eggplant': { name: 'Eggplant', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'pumpkin': { name: 'Pumpkin', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'sweet potato': { name: 'Sweet Potato', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'beetroot': { name: 'Beetroot', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'asparagus': { name: 'Asparagus', status: 'halal', reason: 'Plant-derived vegetable', category: 'Vegetable' },
  'avocado': { name: 'Avocado', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'apple': { name: 'Apple', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'banana': { name: 'Banana', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'orange': { name: 'Orange', status: 'halal', reason: 'Plant-derived citrus fruit', category: 'Fruit' },
  'lemon': { name: 'Lemon', status: 'halal', reason: 'Plant-derived citrus fruit', category: 'Fruit' },
  'lime': { name: 'Lime', status: 'halal', reason: 'Plant-derived citrus fruit', category: 'Fruit' },
  'grape': { name: 'Grape', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'strawberry': { name: 'Strawberry', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'blueberry': { name: 'Blueberry', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'raspberry': { name: 'Raspberry', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'mango': { name: 'Mango', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'pineapple': { name: 'Pineapple', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'peach': { name: 'Peach', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'cherry': { name: 'Cherry', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'cranberry': { name: 'Cranberry', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'fig': { name: 'Fig', status: 'halal', reason: 'Plant-derived fruit — mentioned in Quran', category: 'Fruit' },
  'date': { name: 'Date', status: 'halal', reason: 'Plant-derived fruit — Sunnah food', category: 'Fruit' },
  'pomegranate': { name: 'Pomegranate', status: 'halal', reason: 'Plant-derived fruit — mentioned in Quran', category: 'Fruit' },
  'olive': { name: 'Olive', status: 'halal', reason: 'Plant-derived fruit — mentioned in Quran', category: 'Fruit' },
  'raisin': { name: 'Raisin', status: 'halal', reason: 'Dried grape — plant-derived', category: 'Dried Fruit' },
  'sultana': { name: 'Sultana', status: 'halal', reason: 'Dried grape — plant-derived', category: 'Dried Fruit' },
  'apricot': { name: 'Apricot', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'plum': { name: 'Plum', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'prune': { name: 'Prune', status: 'halal', reason: 'Dried plum — plant-derived', category: 'Dried Fruit' },
  'kiwi': { name: 'Kiwi', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'watermelon': { name: 'Watermelon', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'melon': { name: 'Melon', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'papaya': { name: 'Papaya', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'guava': { name: 'Guava', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'passion fruit': { name: 'Passion Fruit', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'lychee': { name: 'Lychee', status: 'halal', reason: 'Plant-derived fruit', category: 'Fruit' },
  'coconut oil': { name: 'Coconut Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'olive oil': { name: 'Olive Oil', status: 'halal', reason: 'Plant-derived oil — blessed in Islam', category: 'Oil' },
  'vegetable oil': { name: 'Vegetable Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'soybean oil': { name: 'Soybean Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'sesame oil': { name: 'Sesame Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'flaxseed oil': { name: 'Flaxseed Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'avocado oil': { name: 'Avocado Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'peanut oil': { name: 'Peanut Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'corn oil': { name: 'Corn Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'cottonseed oil': { name: 'Cottonseed Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'rice bran oil': { name: 'Rice Bran Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'safflower oil': { name: 'Safflower Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'grape seed oil': { name: 'Grape Seed Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'walnut oil': { name: 'Walnut Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },
  'almond oil': { name: 'Almond Oil', status: 'halal', reason: 'Plant-derived oil', category: 'Oil' },

  // ═══════════════════════════════════════════════════════════════════
  // PROTEINS, LEGUMES, NUTS & SEEDS
  // ═══════════════════════════════════════════════════════════════════
  'peanut': { name: 'Peanut', status: 'halal', reason: 'Plant-derived legume', category: 'Nut/Legume' },
  'almond': { name: 'Almond', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'cashew': { name: 'Cashew', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'walnut': { name: 'Walnut', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'pistachio': { name: 'Pistachio', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'hazelnut': { name: 'Hazelnut', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'macadamia': { name: 'Macadamia', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'pecan': { name: 'Pecan', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'brazil nut': { name: 'Brazil Nut', status: 'halal', reason: 'Plant-derived nut', category: 'Nut' },
  'pine nut': { name: 'Pine Nut', status: 'halal', reason: 'Plant-derived seed', category: 'Nut' },
  'sesame': { name: 'Sesame', status: 'halal', reason: 'Plant-derived seed', category: 'Seed' },
  'flaxseed': { name: 'Flaxseed', status: 'halal', reason: 'Plant-derived seed', category: 'Seed' },
  'chia seed': { name: 'Chia Seed', status: 'halal', reason: 'Plant-derived seed', category: 'Seed' },
  'hemp seed': { name: 'Hemp Seed', status: 'halal', reason: 'Plant-derived seed (non-intoxicating)', category: 'Seed' },
  'pumpkin seed': { name: 'Pumpkin Seed', status: 'halal', reason: 'Plant-derived seed', category: 'Seed' },
  'poppy seed': { name: 'Poppy Seed', status: 'halal', reason: 'Plant-derived seed (non-intoxicating)', category: 'Seed' },
  'lentil': { name: 'Lentil', status: 'halal', reason: 'Plant-derived legume', category: 'Legume' },
  'chickpea': { name: 'Chickpea', status: 'halal', reason: 'Plant-derived legume', category: 'Legume' },
  'kidney bean': { name: 'Kidney Bean', status: 'halal', reason: 'Plant-derived legume', category: 'Legume' },
  'black bean': { name: 'Black Bean', status: 'halal', reason: 'Plant-derived legume', category: 'Legume' },
  'navy bean': { name: 'Navy Bean', status: 'halal', reason: 'Plant-derived legume', category: 'Legume' },
  'lima bean': { name: 'Lima Bean', status: 'halal', reason: 'Plant-derived legume', category: 'Legume' },
  'edamame': { name: 'Edamame', status: 'halal', reason: 'Young soybean — plant-derived', category: 'Legume' },
  'tofu': { name: 'Tofu', status: 'halal', reason: 'From soybeans — plant-derived', category: 'Protein' },
  'tempeh': { name: 'Tempeh', status: 'halal', reason: 'Fermented soybeans — plant-derived', category: 'Protein' },
  'soy sauce': { name: 'Soy Sauce', status: 'halal', reason: 'Fermented soybean condiment — naturally brewed is halal', category: 'Condiment', scholarNote: 'Trace alcohol from fermentation is considered halal by majority of scholars' },
  'miso': { name: 'Miso', status: 'halal', reason: 'Fermented soybean paste', category: 'Condiment' },
  'pea protein': { name: 'Pea Protein', status: 'halal', reason: 'Plant-derived protein', category: 'Protein' },
  'soy protein': { name: 'Soy Protein', status: 'halal', reason: 'Plant-derived protein', category: 'Protein' },
  'wheat protein': { name: 'Wheat Protein', status: 'halal', reason: 'Plant-derived protein (gluten)', category: 'Protein' },
  'rice protein': { name: 'Rice Protein', status: 'halal', reason: 'Plant-derived protein', category: 'Protein' },
  'hemp protein': { name: 'Hemp Protein', status: 'halal', reason: 'Plant-derived protein', category: 'Protein' },
  'whey protein': { name: 'Whey Protein', status: 'halal', reason: 'Dairy-derived protein — halal', category: 'Protein' },
  'casein protein': { name: 'Casein Protein', status: 'halal', reason: 'Milk-derived protein — halal', category: 'Protein' },
  'egg white': { name: 'Egg White', status: 'halal', reason: 'From halal poultry eggs', category: 'Protein' },
  'egg yolk': { name: 'Egg Yolk', status: 'halal', reason: 'From halal poultry eggs', category: 'Protein' },
  'egg': { name: 'Egg', status: 'halal', reason: 'From halal poultry — permissible', category: 'Protein' },
  'egg powder': { name: 'Egg Powder', status: 'halal', reason: 'Dried egg — halal', category: 'Protein' },
  'gluten': { name: 'Gluten', status: 'halal', reason: 'Wheat protein — plant-derived', category: 'Protein' },
  'vital wheat gluten': { name: 'Vital Wheat Gluten', status: 'halal', reason: 'Concentrated wheat protein', category: 'Protein' },

  // ═══════════════════════════════════════════════════════════════════
  // COMMON FOOD ADDITIVES & PROCESSING AIDS
  // ═══════════════════════════════════════════════════════════════════
  'yeast': { name: 'Yeast', status: 'halal', reason: 'Fungal organism used in baking/brewing — halal', category: 'Leavening' },
  'yeast extract': { name: 'Yeast Extract', status: 'halal', reason: 'From yeast — plant/fungal origin', category: 'Flavouring' },
  'nutritional yeast': { name: 'Nutritional Yeast', status: 'halal', reason: 'Deactivated yeast — plant/fungal', category: 'Flavouring' },
  'bakers yeast': { name: 'Baker\'s Yeast', status: 'halal', reason: 'Saccharomyces cerevisiae — fungal', category: 'Leavening' },
  'monosodium glutamate': { name: 'MSG (Monosodium Glutamate)', status: 'halal', reason: 'From fermentation of starch/sugar', category: 'Flavour Enhancer' },
  'msg': { name: 'MSG', status: 'halal', reason: 'Monosodium glutamate — from fermentation', category: 'Flavour Enhancer' },
  'disodium guanylate': { name: 'Disodium Guanylate', status: 'halal', reason: 'Usually from yeast or plant sources', category: 'Flavour Enhancer' },
  'disodium inosinate': { name: 'Disodium Inosinate', status: 'halal', reason: 'Usually from yeast or tapioca', category: 'Flavour Enhancer' },
  'smoke flavour': { name: 'Smoke Flavour', status: 'halal', reason: 'From burning wood — plant-derived', category: 'Flavouring' },
  'liquid smoke': { name: 'Liquid Smoke', status: 'halal', reason: 'Condensed wood smoke — plant-derived', category: 'Flavouring' },
  'caramel': { name: 'Caramel', status: 'halal', reason: 'From heated sugar — plant-derived', category: 'Colour/Flavouring' },
  'caramel colour': { name: 'Caramel Colour', status: 'halal', reason: 'From heated sugar', category: 'Colour' },
  'annatto': { name: 'Annatto', status: 'halal', reason: 'Plant seed extract colour', category: 'Colour' },
  'chlorophyll': { name: 'Chlorophyll', status: 'halal', reason: 'Plant-derived green pigment', category: 'Colour' },
  'activated charcoal': { name: 'Activated Charcoal', status: 'halal', reason: 'From coconut shell or wood', category: 'Processing Aid' },
  'carbon dioxide': { name: 'Carbon Dioxide', status: 'halal', reason: 'Inert gas for carbonation', category: 'Gas' },
  'nitrogen': { name: 'Nitrogen', status: 'halal', reason: 'Inert gas', category: 'Gas' },
  'oxygen': { name: 'Oxygen', status: 'halal', reason: 'Natural gas', category: 'Gas' },
  'caffeine': { name: 'Caffeine', status: 'halal', reason: 'From coffee/tea or synthetic — not intoxicating', category: 'Stimulant' },
  'taurine': { name: 'Taurine', status: 'halal', reason: 'Synthetic amino acid in energy drinks', category: 'Amino Acid' },
  'glucuronolactone': { name: 'Glucuronolactone', status: 'halal', reason: 'Synthetic compound in energy drinks', category: 'Additive' },
  'carnitine': { name: 'Carnitine', status: 'halal', reason: 'Usually synthetic — halal', category: 'Amino Acid' },
  'creatine': { name: 'Creatine', status: 'halal', reason: 'Synthetic amino acid derivative', category: 'Supplement' },
};


// ═══════════════════════════════════════════════════════════════════
// COSMETICS & SKINCARE INGREDIENTS
// ═══════════════════════════════════════════════════════════════════
export const cosmeticsIngredients: Record<string, Ingredient> = {
  'hyaluronic acid': { name: 'Hyaluronic Acid', status: 'halal', reason: 'Usually synthetic or bacterial fermentation', category: 'Cosmetic' },
  'salicylic acid': { name: 'Salicylic Acid', status: 'halal', reason: 'Synthetic or from willow bark', category: 'Cosmetic' },
  'glycolic acid': { name: 'Glycolic Acid', status: 'halal', reason: 'From sugarcane or synthetic', category: 'Cosmetic' },
  'benzoyl peroxide': { name: 'Benzoyl Peroxide', status: 'halal', reason: 'Synthetic compound', category: 'Cosmetic' },
  'retinyl palmitate': { name: 'Retinyl Palmitate', status: 'halal', reason: 'Synthetic vitamin A derivative', category: 'Cosmetic' },
  'dimethicone': { name: 'Dimethicone', status: 'halal', reason: 'Synthetic silicone polymer', category: 'Cosmetic' },
  'cyclomethicone': { name: 'Cyclomethicone', status: 'halal', reason: 'Synthetic silicone', category: 'Cosmetic' },
  'cetyl alcohol': { name: 'Cetyl Alcohol', status: 'halal', reason: 'Fatty alcohol from coconut/palm oil — not intoxicating', category: 'Cosmetic' },
  'cetearyl alcohol': { name: 'Cetearyl Alcohol', status: 'halal', reason: 'Fatty alcohol from plant oils — not intoxicating', category: 'Cosmetic' },
  'stearyl alcohol': { name: 'Stearyl Alcohol', status: 'halal', reason: 'Fatty alcohol from plant oils — not intoxicating', category: 'Cosmetic' },
  'isopropyl alcohol': { name: 'Isopropyl Alcohol', status: 'halal', reason: 'Synthetic rubbing alcohol — not drinkable, external use halal', category: 'Cosmetic', scholarNote: 'Majority of scholars permit non-drinkable alcohols in cosmetics/medicine for external use' },
  'denatured alcohol': { name: 'Denatured Alcohol', status: 'halal', reason: 'Made undrinkable — external use permitted by majority', category: 'Cosmetic', scholarNote: 'Hanafi/Maliki: permitted externally. Some scholars disagree.' },
  'phenoxyethanol': { name: 'Phenoxyethanol', status: 'halal', reason: 'Synthetic preservative — not intoxicating', category: 'Cosmetic' },
  'parabens': { name: 'Parabens', status: 'halal', reason: 'Synthetic preservatives', category: 'Cosmetic' },
  'methylparaben': { name: 'Methylparaben', status: 'halal', reason: 'Synthetic preservative', category: 'Cosmetic' },
  'propylparaben': { name: 'Propylparaben', status: 'halal', reason: 'Synthetic preservative', category: 'Cosmetic' },
  'sodium lauryl sulfate': { name: 'Sodium Lauryl Sulfate (SLS)', status: 'halal', reason: 'Usually from coconut/palm oil', category: 'Cosmetic/Toothpaste' },
  'sodium laureth sulfate': { name: 'Sodium Laureth Sulfate (SLES)', status: 'halal', reason: 'Usually from coconut/palm oil', category: 'Cosmetic/Toothpaste' },
  'cocamidopropyl betaine': { name: 'Cocamidopropyl Betaine', status: 'halal', reason: 'From coconut oil', category: 'Cosmetic' },
  'shea butter': { name: 'Shea Butter', status: 'halal', reason: 'From shea tree nuts — plant-derived', category: 'Cosmetic' },
  'cocoa butter': { name: 'Cocoa Butter', status: 'halal', reason: 'From cacao beans — plant-derived', category: 'Cosmetic' },
  'jojoba oil': { name: 'Jojoba Oil', status: 'halal', reason: 'From jojoba plant seeds', category: 'Cosmetic' },
  'argan oil': { name: 'Argan Oil', status: 'halal', reason: 'From argan tree nuts', category: 'Cosmetic' },
  'tea tree oil': { name: 'Tea Tree Oil', status: 'halal', reason: 'From tea tree leaves', category: 'Cosmetic' },
  'aloe vera': { name: 'Aloe Vera', status: 'halal', reason: 'Plant-derived', category: 'Cosmetic' },
  'witch hazel': { name: 'Witch Hazel', status: 'halal', reason: 'Plant extract', category: 'Cosmetic' },
  'niacinamide': { name: 'Niacinamide (Skincare)', status: 'halal', reason: 'Synthetic vitamin B3', category: 'Cosmetic' },
  'ceramide': { name: 'Ceramide', status: 'halal', reason: 'Usually synthetic or plant-derived', category: 'Cosmetic' },
  'peptide': { name: 'Peptide', status: 'halal', reason: 'Usually synthetic amino acid chains', category: 'Cosmetic' },
  'collagen cream': { name: 'Collagen (Cosmetic)', status: 'mashbooh', reason: 'Source must be verified — may be from pork, bovine, or marine', category: 'Cosmetic', scholarNote: 'Marine collagen and plant-based alternatives are halal' },
  'keratin': { name: 'Keratin', status: 'mashbooh', reason: 'Usually from animal hair/hooves — source must be verified', category: 'Cosmetic' },
  'lanolin': { name: 'Lanolin', status: 'halal', reason: 'From sheep wool grease — does not require slaughter', category: 'Cosmetic', scholarNote: 'Majority consider halal as it is from a living animal without harm' },
  'beeswax': { name: 'Beeswax (Cosmetic)', status: 'halal', reason: 'From bees — halal', category: 'Cosmetic' },
  'carmine lipstick': { name: 'Carmine (in Cosmetics)', status: 'haram', reason: 'From crushed insects — haram per majority', category: 'Cosmetic' },
  'squalane': { name: 'Squalane', status: 'halal', reason: 'Usually from olive oil or sugarcane (plant-derived)', category: 'Cosmetic', scholarNote: 'Shark-derived squalene exists but is rare in modern cosmetics' },
  'panthenol': { name: 'Panthenol (Pro-Vitamin B5)', status: 'halal', reason: 'Synthetic vitamin derivative', category: 'Cosmetic' },
  'allantoin': { name: 'Allantoin', status: 'halal', reason: 'Synthetic or from comfrey plant', category: 'Cosmetic' },
  'urea': { name: 'Urea (Cosmetic)', status: 'halal', reason: 'Synthetic — not from animal urine in cosmetics', category: 'Cosmetic' },
  'zinc pyrithione': { name: 'Zinc Pyrithione', status: 'halal', reason: 'Synthetic anti-dandruff compound', category: 'Cosmetic' },
  'ketoconazole': { name: 'Ketoconazole', status: 'halal', reason: 'Synthetic antifungal', category: 'Medicine' },
  'minoxidil': { name: 'Minoxidil', status: 'halal', reason: 'Synthetic hair growth compound', category: 'Medicine' },

  // ═══════════════════════════════════════════════════════════════════
  // TOOTHPASTE & MOUTHWASH INGREDIENTS
  // ═══════════════════════════════════════════════════════════════════
  'fluoride': { name: 'Fluoride', status: 'halal', reason: 'Mineral compound for dental health', category: 'Toothpaste' },
  'sodium fluoride': { name: 'Sodium Fluoride', status: 'halal', reason: 'Mineral salt for dental health', category: 'Toothpaste' },
  'stannous fluoride': { name: 'Stannous Fluoride', status: 'halal', reason: 'Mineral compound', category: 'Toothpaste' },
  'sodium monofluorophosphate': { name: 'Sodium Monofluorophosphate', status: 'halal', reason: 'Synthetic fluoride compound', category: 'Toothpaste' },
  'sorbitol toothpaste': { name: 'Sorbitol (in Toothpaste)', status: 'halal', reason: 'Plant-derived sugar alcohol', category: 'Toothpaste' },
  'xylitol toothpaste': { name: 'Xylitol (in Toothpaste)', status: 'halal', reason: 'Plant-derived sugar alcohol', category: 'Toothpaste' },
  'hydrated silica': { name: 'Hydrated Silica', status: 'halal', reason: 'Mineral abrasive', category: 'Toothpaste' },
  'calcium carbonate toothpaste': { name: 'Calcium Carbonate (Toothpaste)', status: 'halal', reason: 'Mineral abrasive', category: 'Toothpaste' },
  'sodium saccharin': { name: 'Sodium Saccharin', status: 'halal', reason: 'Synthetic sweetener', category: 'Toothpaste' },
  'cetylpyridinium chloride': { name: 'Cetylpyridinium Chloride (CPC)', status: 'halal', reason: 'Synthetic antiseptic', category: 'Mouthwash' },
  'chlorhexidine': { name: 'Chlorhexidine', status: 'halal', reason: 'Synthetic antiseptic', category: 'Mouthwash' },
  'hydrogen peroxide': { name: 'Hydrogen Peroxide', status: 'halal', reason: 'Synthetic oxidising agent', category: 'Mouthwash/Cosmetic' },
  'triclosan': { name: 'Triclosan', status: 'halal', reason: 'Synthetic antibacterial', category: 'Toothpaste' },

  // ═══════════════════════════════════════════════════════════════════
  // MEDICINE & SUPPLEMENT INGREDIENTS
  // ═══════════════════════════════════════════════════════════════════
  'paracetamol': { name: 'Paracetamol (Acetaminophen)', status: 'halal', reason: 'Synthetic pain reliever', category: 'Medicine' },
  'ibuprofen': { name: 'Ibuprofen', status: 'halal', reason: 'Synthetic anti-inflammatory', category: 'Medicine' },
  'aspirin': { name: 'Aspirin', status: 'halal', reason: 'Synthetic from salicylic acid', category: 'Medicine' },
  'amoxicillin': { name: 'Amoxicillin', status: 'halal', reason: 'Synthetic antibiotic', category: 'Medicine' },
  'metformin': { name: 'Metformin', status: 'halal', reason: 'Synthetic diabetes medication', category: 'Medicine' },
  'omeprazole': { name: 'Omeprazole', status: 'halal', reason: 'Synthetic acid reducer', category: 'Medicine' },
  'cetirizine': { name: 'Cetirizine', status: 'halal', reason: 'Synthetic antihistamine', category: 'Medicine' },
  'loratadine': { name: 'Loratadine', status: 'halal', reason: 'Synthetic antihistamine', category: 'Medicine' },
  'dextromethorphan': { name: 'Dextromethorphan', status: 'halal', reason: 'Synthetic cough suppressant', category: 'Medicine' },
  'guaifenesin': { name: 'Guaifenesin', status: 'halal', reason: 'Synthetic expectorant', category: 'Medicine' },
  'pseudoephedrine': { name: 'Pseudoephedrine', status: 'halal', reason: 'Synthetic decongestant', category: 'Medicine' },
  'loperamide': { name: 'Loperamide', status: 'halal', reason: 'Synthetic anti-diarrheal', category: 'Medicine' },
  'simethicone': { name: 'Simethicone', status: 'halal', reason: 'Synthetic anti-gas agent', category: 'Medicine' },
  'gelatin capsule': { name: 'Gelatin Capsule', status: 'haram', reason: 'Usually from pork or non-halal bovine gelatin', category: 'Medicine', scholarNote: 'Look for vegetable capsules (HPMC/pullulan) or halal-certified gelatin capsules' },
  'hpmc capsule': { name: 'HPMC Capsule (Vegetable)', status: 'halal', reason: 'Hydroxypropyl methylcellulose — plant-derived capsule', category: 'Medicine' },
  'vegetable capsule': { name: 'Vegetable Capsule', status: 'halal', reason: 'Plant-derived cellulose capsule — halal alternative to gelatin', category: 'Medicine' },
  'pullulan capsule': { name: 'Pullulan Capsule', status: 'halal', reason: 'From fungal fermentation — halal capsule', category: 'Medicine' },
  'fish oil': { name: 'Fish Oil', status: 'halal', reason: 'From fish — halal', category: 'Supplement' },
  'cod liver oil': { name: 'Cod Liver Oil', status: 'halal', reason: 'From fish — halal', category: 'Supplement' },
  'omega 3': { name: 'Omega-3', status: 'halal', reason: 'Usually from fish oil or algae — halal', category: 'Supplement' },
  'omega 6': { name: 'Omega-6', status: 'halal', reason: 'Usually from plant oils', category: 'Supplement' },
  'probiotics': { name: 'Probiotics', status: 'halal', reason: 'Beneficial bacteria — halal', category: 'Supplement' },
  'lactobacillus': { name: 'Lactobacillus', status: 'halal', reason: 'Probiotic bacteria', category: 'Supplement' },
  'bifidobacterium': { name: 'Bifidobacterium', status: 'halal', reason: 'Probiotic bacteria', category: 'Supplement' },
  'glucosamine': { name: 'Glucosamine', status: 'mashbooh', reason: 'Can be from shellfish (halal) or synthetic — verify if from pork', category: 'Supplement', scholarNote: 'Shellfish-derived and synthetic glucosamine are halal' },
  'chondroitin': { name: 'Chondroitin', status: 'mashbooh', reason: 'Usually from animal cartilage — source must be verified', category: 'Supplement' },
  'coenzyme q10': { name: 'Coenzyme Q10 (CoQ10)', status: 'halal', reason: 'Usually from yeast fermentation', category: 'Supplement' },
  'melatonin': { name: 'Melatonin', status: 'halal', reason: 'Synthetic sleep hormone', category: 'Supplement' },
  'collagen supplement': { name: 'Collagen Supplement', status: 'mashbooh', reason: 'Source must be verified — bovine/marine halal, pork haram', category: 'Supplement' },

  // ═══════════════════════════════════════════════════════════════════
  // BABY PRODUCT INGREDIENTS
  // ═══════════════════════════════════════════════════════════════════
  'zinc oxide baby': { name: 'Zinc Oxide (Baby Cream)', status: 'halal', reason: 'Mineral compound — safe and halal', category: 'Baby Product' },
  'petroleum jelly': { name: 'Petroleum Jelly (Vaseline)', status: 'halal', reason: 'Mineral oil derivative — halal', category: 'Baby Product' },
  'mineral oil': { name: 'Mineral Oil', status: 'halal', reason: 'Petroleum-derived — halal', category: 'Baby Product' },
  'baby formula': { name: 'Baby Formula', status: 'halal', reason: 'Usually plant/dairy-based — check for DHA source', category: 'Baby Product', scholarNote: 'Check if DHA is from fish oil (halal) or algae (halal). Avoid if contains pork-derived ingredients.' },
  'dha': { name: 'DHA (Docosahexaenoic Acid)', status: 'halal', reason: 'Usually from fish oil or algae', category: 'Baby Product/Supplement' },
  'ara': { name: 'ARA (Arachidonic Acid)', status: 'halal', reason: 'Usually from fungal fermentation', category: 'Baby Product/Supplement' },
  'lactose baby': { name: 'Lactose (in Baby Formula)', status: 'halal', reason: 'Milk sugar — halal', category: 'Baby Product' },
  'whey baby': { name: 'Whey (in Baby Formula)', status: 'halal', reason: 'Dairy protein — halal', category: 'Baby Product' },

  // ═══════════════════════════════════════════════════════════════════
  // ADDITIONAL HARAM/MASHBOOH ITEMS (COSMETICS/MEDICINE)
  // ═══════════════════════════════════════════════════════════════════
  'musk deer': { name: 'Musk (Animal-Derived)', status: 'haram', reason: 'From musk deer gland — animal killed for extraction', category: 'Cosmetic' },
  'ambergris': { name: 'Ambergris', status: 'mashbooh', reason: 'From sperm whale — scholars differ on permissibility', category: 'Cosmetic' },
  'civet': { name: 'Civet', status: 'haram', reason: 'From civet cat glands — animal cruelty involved', category: 'Cosmetic' },
  'placenta extract': { name: 'Placenta Extract', status: 'haram', reason: 'From animal or human placenta', category: 'Cosmetic' },
  'snail mucin': { name: 'Snail Mucin', status: 'halal', reason: 'From snails — majority consider halal for external use', category: 'Cosmetic' },
  'silk protein': { name: 'Silk Protein', status: 'halal', reason: 'From silkworm — majority consider halal', category: 'Cosmetic' },
  'pearl powder': { name: 'Pearl Powder', status: 'halal', reason: 'From oyster shells — halal', category: 'Cosmetic' },
  'propolis': { name: 'Propolis', status: 'halal', reason: 'From bees — halal like honey', category: 'Supplement/Cosmetic' },
  'royal jelly': { name: 'Royal Jelly', status: 'halal', reason: 'From bees — halal like honey', category: 'Supplement' },
};
